import React, { useMemo, useRef, useState, useEffect, useCallback, createContext, useContext } from 'react';
import { X, Search, Maximize2, Minimize2, RotateCcw, ScrollText } from 'lucide-react';
import {
  ReactFlow,
  MiniMap,
  Controls,
  Background,
  BackgroundVariant,
  MarkerType,
  Position,
  Handle,
  applyNodeChanges,
  type Node,
  type Edge,
  type NodeChange,
  type NodeProps,
  type ReactFlowInstance,
  type Connection,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useDesignerStore } from '../store';
import { t } from '../i18n';
import type { ViewInfo, ViewEdgeInfo, NavEditEdgeLocator, NavEditRequestBody, NavEditErrorCode } from '../types';
import { SWITCH_OUT_STYLES, SWITCH_IN_STYLES, type EventType } from '../../hml/eventTypes';
import './ViewRelationModal.css';

interface ViewRelationModalProps {
  visible: boolean;
  onClose: () => void;
}

// 配色统一走主题变量（局部变量在 ViewRelationModal.css 的 .vrm-overlay 上定义，
// 由 --vscode-charts-* 派生并带回退链；禁止硬编码颜色）
const COLOR_VALID = 'var(--vrm-color-valid)';
const COLOR_INVALID = 'var(--vrm-color-invalid)';
const COLOR_AMBIGUOUS = 'var(--vrm-color-ambiguous)';
const COLOR_CURRENT = 'var(--vscode-focusBorder)';
const COLOR_NODE_DEFAULT = 'var(--vscode-editorWidget-border, var(--vscode-panel-border))';

// 默认淡出/正常/高亮透明度（全局图默认低透明度，悬停高亮相关边）
const OVERVIEW_EDGE_OPACITY_DEFAULT = 0.1;
const OVERVIEW_EDGE_OPACITY_FADED = 0.04;
const FOCUS_EDGE_OPACITY_DEFAULT = 0.85;
const FOCUS_EDGE_OPACITY_FADED = 0.3;
const EDGE_OPACITY_HIGHLIGHT = 1;

// 节点拖动结束后的布局写盘防抖间隔（T7）
const LAYOUT_SAVE_DEBOUNCE_MS = 800;

// ---------------- 节点数据模型 ----------------

type ViewNodeKind = 'view' | 'missing' | 'ambiguous';

interface ViewNodeData extends Record<string, unknown> {
  name: string;
  fileLabel: string;      // 文件相对路径（T2 fileRelative；旧数据回退 basename）
  isCurrentFile: boolean;
  kind: ViewNodeKind;     // view=真实屏；missing=无效目标占位；ambiguous=歧义目标占位
  invalidOut: number;     // 出边中无效目标条数
  ambiguousOut: number;   // 出边中歧义目标条数
  autoId: boolean;        // id 为解析器自动生成（建议补显式 id）
  bidirectional?: boolean; // 聚焦子图中既是前驱又是后继（只放左列并标徽记，渲染期计算）
}

type ViewFlowNode = Node<ViewNodeData, 'viewCard'>;

// ---------------- 边数据模型 ----------------

interface ViewEdgeData extends Record<string, unknown> {
  sourceId: string;
  targetId: string;
  isTimer: boolean;
  invalid: boolean;
  ambiguous: boolean;
  shortLabel: string;    // 全局图标签：触发控件 · 手势
  expandedLabel: string; // 聚焦模式标签：触发控件 · 事件 · 动画
  raw: ViewEdgeInfo;     // T2 原始边数据（T11 编辑定位用）
  canReconnect: boolean; // 可拖目标端改跳转（非定时器、非歧义、定位字段齐全）
  canDelete: boolean;    // 可删除（非定时器、定位字段齐全）
}

type ViewFlowEdge = Edge<ViewEdgeData>;

// ---------------- 工具函数 ----------------

/** 路径规范化比较（统一正斜杠 + 忽略大小写，Windows 盘符/分隔符差异不敏感） */
const normalizePath = (p: string): string => p.replace(/\\/g, '/').toLowerCase();

/** 节点 id：viewKey 复合键（relPath#viewId）；旧数据回退 file#id */
const nodeIdOf = (view: ViewInfo): string => view.viewKey || `${view.file}#${view.id}`;

/** 解析器确定性 fallback id 形如 `${basename}_hg_view_auto_N` / `hg_view_auto_N` */
const isAutoGeneratedId = (id: string): boolean => /(^|_)hg_view_auto_\d+$/.test(id);

/** 真实屏节点判定：missing:/ambiguous: 占位节点不可作为连接端点（T11） */
const isRealViewNodeId = (id: string | null | undefined): boolean =>
  !!id && !id.startsWith('missing:') && !id.startsWith('ambiguous:');

/** 复合键 relPath#viewId → 裸 view id（switchView 的 target 用裸 id） */
const bareViewId = (viewKey: string): string => viewKey.slice(viewKey.indexOf('#') + 1);

/**
 * 从 T2 边数据提取写事务定位键（T11 → T10 applyNavEdit 入参）。
 * 定位字段不齐（旧数据 / 快照缺失）返回 null，编辑操作降级禁用。
 */
const locatorOf = (e: ViewEdgeInfo): NavEditEdgeLocator | null => {
  if (!e.sourceViewKey || !e.sourceControlId
    || typeof e.eventConfigIndex !== 'number' || e.eventConfigIndex < 0
    || typeof e.actionIndex !== 'number' || e.actionIndex < 0
    || (!e.sourceFileHash && typeof e.sourceFileMtime !== 'number')) {
    return null;
  }
  return {
    sourceViewKey: e.sourceViewKey,
    sourceControlId: e.sourceControlId,
    eventType: e.eventType || e.event,
    eventConfigIndex: e.eventConfigIndex,
    actionIndex: e.actionIndex,
    target: e.target,
    sourceIsView: e.sourceIsView,
    sourceIsTimer: e.sourceIsTimer,
    sourceFileMtime: e.sourceFileMtime,
    sourceFileHash: e.sourceFileHash,
  };
};

/** 事件类型 → 本地化标签（复用 event.* i18n key，缺失回退原始值） */
const eventLabel = (type: string): string => {
  const key = `event.${type}`;
  const label = t(key as Parameters<typeof t>[0]);
  return label === key ? type : label;
};

const SWITCH_OUT_DEFAULT = 'SWITCH_OUT_TO_LEFT_USE_TRANSLATION';
const SWITCH_IN_DEFAULT = 'SWITCH_IN_FROM_RIGHT_USE_TRANSLATION';

/** 切换动画枚举值 → 本地化标签（缺失回退默认动画） */
const styleLabel = (
  list: { value: string; labelKey: string }[],
  value: string | undefined,
  fallback: string
): string => {
  const v = value || fallback;
  const found = list.find(s => s.value === v);
  return found ? t(found.labelKey as Parameters<typeof t>[0]) : v;
};

/** 出/入动画组合标签，用于聚焦模式展开的 `触发控件·事件·动画` */
const animationLabelOf = (e: ViewEdgeInfo): string => {
  const out = styleLabel(SWITCH_OUT_STYLES, e.switchOutStyle, SWITCH_OUT_DEFAULT);
  const inn = styleLabel(SWITCH_IN_STYLES, e.switchInStyle, SWITCH_IN_DEFAULT);
  return `${out} → ${inn}`;
};

/** round-trip 预检差异种类 → 可读文案（T11 needsConfirm 确认弹窗） */
const rewriteReasonLabel = (reason: string): string =>
  reason === 'comments'
    ? t('navEdit.loss.comments')
    : reason === 'unknownTags'
      ? t('navEdit.loss.unknownTags')
      : reason === 'nameAttributes'
        ? t('navEdit.loss.nameAttributes')
        : reason;

// ---------------- 自定义节点：屏卡片 ----------------

// 悬停淡出集合经 Context 下发（值为高亮节点 id 集合；null=无悬停）。
// 不通过重建 node 对象传 dimmed：React Flow 受控模式下，每次悬停变化都
// map 出全新 node 对象会让 React Flow 对未测量对象反复派发 dimensions
// 变更 → onNodesChange → setNodes → 重渲染，形成自激刷新风暴（聚焦模式实测复现）。
const HoverDimContext = createContext<Set<string> | null>(null);

const ViewCardNode: React.FC<NodeProps<ViewFlowNode>> = ({ id, data, isConnectable }) => {
  const hoverIds = useContext(HoverDimContext);
  const classes = ['vrm-node', `vrm-node-${data.kind}`];
  if (data.isCurrentFile) {
    classes.push('vrm-node-current');
  }
  if (hoverIds !== null && !hoverIds.has(id)) {
    classes.push('vrm-node-dimmed');
  }
  const hasBadges = data.invalidOut > 0 || data.ambiguousOut > 0 || data.autoId || data.bidirectional === true;
  // 占位节点（无效/歧义目标）悬停解释错在哪、怎么修
  const cardTitle = data.kind === 'missing'
    ? t('navNode.tooltip.missing', data.name)
    : data.kind === 'ambiguous'
      ? t('navNode.tooltip.ambiguous', data.name)
      : undefined;
  return (
    <div className={classes.join(' ')} title={cardTitle}>
      <Handle type="target" position={Position.Left} className="vrm-handle" isConnectable={isConnectable} />
      <div className="vrm-node-name" title={data.name}>
        {data.isCurrentFile && <span className="vrm-node-star">★</span>}
        <span className="vrm-node-name-text">{data.name}</span>
      </div>
      <div className="vrm-node-file" title={data.fileLabel}>
        {data.kind === 'view'
          ? data.fileLabel
          : data.kind === 'missing'
            ? t('Target not found')
            : t('Ambiguous target')}
      </div>
      {hasBadges && (
        <div className="vrm-node-badges">
          {data.invalidOut > 0 && (
            <span className="vrm-badge vrm-badge-invalid" title={t('Has invalid jump target')}>
              ⚠ {data.invalidOut}
            </span>
          )}
          {data.ambiguousOut > 0 && (
            <span className="vrm-badge vrm-badge-ambiguous" title={t('Has ambiguous jump target')}>
              ⚠ {data.ambiguousOut}
            </span>
          )}
          {data.autoId && (
            <span className="vrm-badge vrm-badge-autoid" title={t('View has no id, consider adding one')}>
              id?
            </span>
          )}
          {data.bidirectional === true && (
            <span className="vrm-badge vrm-badge-bidirectional" title={t('Both predecessor and successor of the focused view')}>
              ⇄ {t('Bidirectional')}
            </span>
          )}
        </div>
      )}
      <Handle type="source" position={Position.Right} className="vrm-handle" isConnectable={isConnectable} />
    </div>
  );
};

const nodeTypes = { viewCard: ViewCardNode };

// ---------------- 图构建 ----------------

interface GraphSeed {
  id: string;
  data: ViewNodeData;
}

interface GraphModel {
  seeds: GraphSeed[]; // 已按种子布局顺序排序（当前文件优先 → 相对路径 → 名称；占位节点殿后）
  edges: ViewFlowEdge[];
  viewCount: number;
  edgeCount: number;
}

const buildGraph = (allViews: ViewInfo[] | undefined, currentFilePath: string | undefined): GraphModel => {
  const views = allViews || [];
  const cur = currentFilePath ? normalizePath(currentFilePath) : '';

  const isCurrentFile = (v: ViewInfo): boolean => {
    if (!cur) {
      return false;
    }
    if (v.filePath) {
      return normalizePath(v.filePath) === cur;
    }
    // 旧数据无绝对路径：回退 basename 比较
    const base = (cur.split('/').pop() || '').replace(/\.hml$/, '');
    return base !== '' && base === v.file.toLowerCase();
  };

  const fileLabelOf = (v: ViewInfo): string => v.fileRelative || v.file;

  // 种子布局排序：当前文件优先 → 相对路径 → 名称
  const ordered = [...views].sort((a, b) => {
    const aCur = isCurrentFile(a);
    const bCur = isCurrentFile(b);
    if (aCur !== bCur) {
      return aCur ? -1 : 1;
    }
    const fileCmp = fileLabelOf(a).localeCompare(fileLabelOf(b));
    if (fileCmp !== 0) {
      return fileCmp;
    }
    return a.name.localeCompare(b.name);
  });

  const edges: ViewFlowEdge[] = [];
  const edgeIds = new Set<string>();
  // 占位节点：无效 / 歧义目标（保证每条 T2 边都可见）
  const synthetic = new Map<string, GraphSeed>();
  const invalidOutBy = new Map<string, number>();
  const ambiguousOutBy = new Map<string, number>();
  const seenNodeIds = new Set<string>();
  const seeds: GraphSeed[] = [];

  for (const view of ordered) {
    const id = nodeIdOf(view);
    if (seenNodeIds.has(id)) {
      continue; // 防御：复合键理论上唯一
    }
    seenNodeIds.add(id);
    seeds.push({
      id,
      data: {
        name: view.name,
        fileLabel: fileLabelOf(view),
        isCurrentFile: isCurrentFile(view),
        kind: 'view',
        invalidOut: 0,
        ambiguousOut: 0,
        autoId: isAutoGeneratedId(view.id),
      },
    });
  }

  for (const view of ordered) {
    const sourceId = nodeIdOf(view);
    (view.edges || []).forEach((e, ei) => {
      if (!e.target) {
        return;
      }
      const isTimer = e.sourceIsTimer === true || (e.eventType || e.event) === 'timer';
      const invalid = e.isValid === false;
      const ambiguous = e.targetAmbiguous === true;

      let targetNodeId: string;
      if (invalid) {
        targetNodeId = `missing:${e.target}`;
        invalidOutBy.set(sourceId, (invalidOutBy.get(sourceId) || 0) + 1);
      } else if (ambiguous || !e.targetViewKey) {
        // 歧义（或旧数据未解析出目标复合键）→ 歧义占位节点
        targetNodeId = `ambiguous:${e.target}`;
        ambiguousOutBy.set(sourceId, (ambiguousOutBy.get(sourceId) || 0) + 1);
      } else {
        targetNodeId = e.targetViewKey;
      }

      if (targetNodeId.startsWith('missing:') || targetNodeId.startsWith('ambiguous:')) {
        if (!synthetic.has(targetNodeId)) {
          synthetic.set(targetNodeId, {
            id: targetNodeId,
            data: {
              name: e.target,
              fileLabel: '',
              isCurrentFile: false,
              kind: targetNodeId.startsWith('missing:') ? 'missing' : 'ambiguous',
              invalidOut: 0,
              ambiguousOut: 0,
              autoId: false,
            },
          });
        }
      }

      // 边标签：触发控件 · 手势（定时器边标注"定时器触发"）；聚焦模式再拼接动画
      const controlPart = e.sourceIsView
        ? t('Screen')
        : (e.sourceControlName || e.sourceControlId || '');
      const triggerPart = isTimer ? t('Timer trigger') : eventLabel(e.eventType || e.event);
      const shortLabel = controlPart ? `${controlPart} · ${triggerPart}` : triggerPart;
      const expandedLabel = `${shortLabel} · ${animationLabelOf(e)}`;

      const color = invalid ? COLOR_INVALID : ambiguous ? COLOR_AMBIGUOUS : COLOR_VALID;
      let edgeId = e.edgeId || `${sourceId}->${e.target}@${ei}`;
      if (edgeIds.has(edgeId)) {
        edgeId = `${edgeId}@${ei}`;
      }
      edgeIds.add(edgeId);

      const classNames = ['vrm-edge'];
      if (invalid) {
        classNames.push('vrm-edge-invalid');
      } else if (ambiguous) {
        classNames.push('vrm-edge-ambiguous');
      }
      if (isTimer) {
        classNames.push('vrm-edge-timer');
      }

      // T11 编辑能力：定位字段齐全才可写（旧数据/快照缺失降级只读）；
      // 定时器边全程只读；歧义 target 禁止改目标（约束 4），允许删除
      const hasLocator = locatorOf(e) !== null;
      const canReconnect = hasLocator && !isTimer && !ambiguous;
      const canDelete = hasLocator && !isTimer;

      edges.push({
        id: edgeId,
        source: sourceId,
        target: targetNodeId,
        label: shortLabel,
        className: classNames.join(' '),
        // 只允许拖目标端改目标（源端由控件归属决定，不可改）
        reconnectable: canReconnect ? ('target' as const) : false,
        style: {
          stroke: color,
          strokeWidth: 1.5,
          opacity: OVERVIEW_EDGE_OPACITY_DEFAULT,
          ...(isTimer ? { strokeDasharray: '6 4' } : {}),
        },
        markerEnd: { type: MarkerType.ArrowClosed, color, width: 16, height: 16 },
        data: {
          sourceId,
          targetId: targetNodeId,
          isTimer,
          invalid,
          ambiguous,
          shortLabel,
          expandedLabel,
          raw: e,
          canReconnect,
          canDelete,
        },
      });
    });
  }

  // 回填出边告警计数
  for (const seed of seeds) {
    seed.data.invalidOut = invalidOutBy.get(seed.id) || 0;
    seed.data.ambiguousOut = ambiguousOutBy.get(seed.id) || 0;
  }

  // 占位节点殿后，按名称排序
  const syntheticSeeds = [...synthetic.values()].sort((a, b) => a.data.name.localeCompare(b.data.name));

  return {
    seeds: [...seeds, ...syntheticSeeds],
    edges,
    viewCount: views.length,
    edgeCount: edges.length,
  };
};

// 种子网格布局：≈√(1.6n) 列的紧凑网格（同文件 view 因排序相邻聚拢）
const GRID_CELL_W = 260;
const GRID_CELL_H = 130;

// 聚焦子图布局：左入右出（前驱居左，焦点居中，后继居右）
const FOCUS_COL_GAP = 340;
const FOCUS_ROW_GAP = 120;

const seedNodes = (
  seeds: GraphSeed[],
  savedPositions: Map<string, { x: number; y: number }>
): ViewFlowNode[] => {
  const cols = Math.max(1, Math.round(Math.sqrt(seeds.length * 1.6)));
  return seeds.map((seed, i) => ({
    id: seed.id,
    type: 'viewCard' as const,
    // T11：占位节点（missing/ambiguous）不可作为连接端点
    connectable: seed.data.kind === 'view',
    position: savedPositions.get(seed.id) || {
      x: (i % cols) * GRID_CELL_W,
      y: Math.floor(i / cols) * GRID_CELL_H,
    },
    data: seed.data,
  }));
};

const minimapNodeColor = (node: Node): string => {
  const data = node.data as ViewNodeData | undefined;
  if (data?.kind === 'missing') {
    return COLOR_INVALID;
  }
  if (data?.kind === 'ambiguous') {
    return COLOR_AMBIGUOUS;
  }
  if (data?.isCurrentFile) {
    return COLOR_CURRENT;
  }
  return COLOR_NODE_DEFAULT;
};

interface FocusView {
  nodes: ViewFlowNode[];
  edges: ViewFlowEdge[];
}

/** 焦点 + 直接前驱 + 直接后继 子图，左入右出布局 */
const buildFocusView = (
  focusId: string,
  seedById: Map<string, GraphSeed>,
  allEdges: ViewFlowEdge[]
): FocusView | null => {
  const focusSeed = seedById.get(focusId);
  if (!focusSeed) {
    return null;
  }

  const predecessorIds: string[] = [];
  const successorIds: string[] = [];
  const seenPred = new Set<string>();
  const seenSucc = new Set<string>();
  const relatedEdges = new Map<string, ViewFlowEdge>();

  for (const edge of allEdges) {
    const isIncoming = edge.target === focusId;
    const isOutgoing = edge.source === focusId;
    if (!isIncoming && !isOutgoing) {
      continue;
    }
    relatedEdges.set(edge.id, edge);
    if (isIncoming && edge.source !== focusId && !seenPred.has(edge.source)) {
      seenPred.add(edge.source);
      predecessorIds.push(edge.source);
    }
    if (isOutgoing && edge.target !== focusId && !seenSucc.has(edge.target)) {
      seenSucc.add(edge.target);
      successorIds.push(edge.target);
    }
  }

  // 同一邻居既是前驱又是后继时只放一列（左列）并标"双向"徽记：
  // 同一 id 出现在两列会产生重复节点 id，React Flow nodeLookup 去重后只渲染
  // 后注册的那份，左列该行空缺、前驱边反向画回交点。两条边都保留指向该节点。
  const successorOnlyIds = successorIds.filter(id => !seenPred.has(id));

  const nodes: ViewFlowNode[] = [];
  predecessorIds.forEach((id, i) => {
    const seed = seedById.get(id);
    if (!seed) {
      return;
    }
    const bidirectional = seenSucc.has(id);
    nodes.push({
      id,
      type: 'viewCard',
      connectable: seed.data.kind === 'view',
      position: { x: 0, y: i * FOCUS_ROW_GAP },
      data: bidirectional ? { ...seed.data, bidirectional: true } : seed.data,
    });
  });

  const centerRowCount = Math.max(predecessorIds.length, successorOnlyIds.length, 1);
  nodes.push({
    id: focusId,
    type: 'viewCard',
    connectable: focusSeed.data.kind === 'view',
    position: { x: FOCUS_COL_GAP, y: ((centerRowCount - 1) * FOCUS_ROW_GAP) / 2 },
    data: focusSeed.data,
  });

  successorOnlyIds.forEach((id, i) => {
    const seed = seedById.get(id);
    if (!seed) {
      return;
    }
    nodes.push({
      id,
      type: 'viewCard',
      connectable: seed.data.kind === 'view',
      position: { x: FOCUS_COL_GAP * 2, y: i * FOCUS_ROW_GAP },
      data: seed.data,
    });
  });

  const edges: ViewFlowEdge[] = [...relatedEdges.values()].map(edge => ({
    ...edge,
    label: edge.data?.expandedLabel ?? edge.label,
  }));

  return { nodes, edges };
};

// ---------------- 弹窗:可拖拽 + 可调大小(T5) ----------------

interface DialogRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

const DIALOG_MIN_W = 640;
const DIALOG_MIN_H = 420;
const DIALOG_DEFAULT_MAX_W = 1680;
const DIALOG_DEFAULT_MAX_H = 1000;
// 最大化时距视口边缘的留白
const DIALOG_MAXIMIZED_MARGIN = 8;
const DIALOG_VIEWPORT_RATIO_W = 0.94;
const DIALOG_VIEWPORT_RATIO_H = 0.92;

/** 最大化矩形：占满视口，四边留固定留白 */
const computeMaximizedDialogRect = (): DialogRect => ({
  x: DIALOG_MAXIMIZED_MARGIN,
  y: DIALOG_MAXIMIZED_MARGIN,
  width: Math.max(DIALOG_MIN_W, window.innerWidth - DIALOG_MAXIMIZED_MARGIN * 2),
  height: Math.max(DIALOG_MIN_H, window.innerHeight - DIALOG_MAXIMIZED_MARGIN * 2),
});

/** 打开时居中的默认尺寸：min(1680px,94vw) × min(1000px,92vh)，不低于最小尺寸 */
const computeDefaultDialogRect = (): DialogRect => {
  const width = Math.max(DIALOG_MIN_W, Math.min(DIALOG_DEFAULT_MAX_W, window.innerWidth * DIALOG_VIEWPORT_RATIO_W));
  const height = Math.max(DIALOG_MIN_H, Math.min(DIALOG_DEFAULT_MAX_H, window.innerHeight * DIALOG_VIEWPORT_RATIO_H));
  return {
    width,
    height,
    x: Math.max(0, (window.innerWidth - width) / 2),
    y: Math.max(0, (window.innerHeight - height) / 2),
  };
};

/** 拖动后限制标题栏至少部分可见，避免弹窗整体飘出可视区域 */
const clampDialogPosition = (rect: DialogRect): DialogRect => {
  const minVisible = 160;
  const minX = -(rect.width - minVisible);
  const maxX = window.innerWidth - minVisible;
  const minY = 0;
  const maxY = Math.max(0, window.innerHeight - 48);
  return {
    ...rect,
    x: Math.min(maxX, Math.max(minX, rect.x)),
    y: Math.min(maxY, Math.max(minY, rect.y)),
  };
};

// ---------------- 弹窗组件 ----------------

export const ViewRelationModal: React.FC<ViewRelationModalProps> = ({ visible, onClose }) => {
  const allViews = useDesignerStore(s => s.allViews);
  const currentFilePath = useDesignerStore(s => s.currentFilePath);
  const refreshNavGraph = useDesignerStore(s => s.refreshNavGraph);
  // 节点布局持久化（T7）：宿主读回 <projectRoot>/.honeygui/nav-layout.json
  const navLayout = useDesignerStore(s => s.navLayout);
  const requestNavLayout = useDesignerStore(s => s.requestNavLayout);
  const saveNavLayout = useDesignerStore(s => s.saveNavLayout);
  const navLayoutSaveError = useDesignerStore(s => s.navLayoutSaveError);
  const clearNavLayoutSaveError = useDesignerStore(s => s.clearNavLayoutSaveError);
  // 编辑交互（T11）：写事务 + 新建跳转选择器数据（T9）
  const applyNavEdit = useDesignerStore(s => s.applyNavEdit);
  const navEditPending = useDesignerStore(s => s.navEditPending);
  const navEditResult = useDesignerStore(s => s.navEditResult);
  const clearNavEditResult = useDesignerStore(s => s.clearNavEditResult);
  const viewControls = useDesignerStore(s => s.viewControls);
  const viewControlsForKey = useDesignerStore(s => s.viewControlsForKey);
  const viewControlsError = useDesignerStore(s => s.viewControlsError);
  const requestViewControls = useDesignerStore(s => s.requestViewControls);
  const clearViewControls = useDesignerStore(s => s.clearViewControls);
  // 图内撤销（宿主全局撤销栈，跨面板；条数经回执/查询回推维护）
  const navUndoCount = useDesignerStore(s => s.navUndoCount);
  const undoNavEdit = useDesignerStore(s => s.undoNavEdit);
  const requestNavUndoState = useDesignerStore(s => s.requestNavUndoState);
  // 右键"打开所在页面"：切文件（加载完成后自动选中控件）/ 同文件直接选中
  const openFileInDesigner = useDesignerStore(s => s.openFileInDesigner);
  const selectComponent = useDesignerStore(s => s.selectComponent);
  const showHostLog = useDesignerStore(s => s.showHostLog);

  const [nodes, setNodes] = useState<ViewFlowNode[]>([]);
  // 拖动位置暂存（组件内存态；已加载的持久化布局在到达时合并进来，未知 key 回退种子布局）
  const positionsRef = useRef(new Map<string, { x: number; y: number }>());
  const rfInstanceRef = useRef<ReactFlowInstance<ViewFlowNode, ViewFlowEdge> | null>(null);
  const lastSigRef = useRef('');
  // 进入聚焦子图后等待节点完成首次测量再补跑 fitView（防止空白画布）
  const needsFitRef = useRef(false);
  // T7：已应用过的持久化布局对象引用，避免同一份 navLayout 重复合并
  const appliedNavLayoutRef = useRef<Record<string, { x: number; y: number }> | null>(null);
  // T7：拖动结束后待写盘的 key（防抖聚合，只上报被拖动过的节点）
  const pendingLayoutSaveRef = useRef(new Map<string, { x: number; y: number }>());
  const layoutSaveTimerRef = useRef<number | null>(null);

  // 弹窗可拖拽 + 可调大小（T5）：受控 position/size，打开时居中
  const [dialogRect, setDialogRect] = useState<DialogRect>(() => computeDefaultDialogRect());
  // 最大化/还原（视图多时全屏看图）；还原时回到最大化前的矩形
  const [isMaximized, setIsMaximized] = useState(false);
  const restoreRectRef = useRef<DialogRect | null>(null);
  const toggleMaximize = useCallback(() => {
    setIsMaximized(prev => {
      if (prev) {
        setDialogRect(restoreRectRef.current ? clampDialogPosition(restoreRectRef.current) : computeDefaultDialogRect());
        return false;
      }
      setDialogRect(current => {
        restoreRectRef.current = current;
        return computeMaximizedDialogRect();
      });
      return true;
    });
  }, []);
  // 拖动/调整大小进行中：禁用文本选中、隔离图层 pan/zoom 手势
  const [isInteracting, setIsInteracting] = useState(false);
  // 拖动/缩放在遮罩上释放指针时，浏览器会派发一次合成 click（target=遮罩），
  // 会误触发遮罩的关闭逻辑——拖拽结束后一帧内忽略遮罩 click
  const suppressOverlayClickRef = useRef(false);
  const armSuppressOverlayClick = useCallback(() => {
    suppressOverlayClickRef.current = true;
    window.requestAnimationFrame(() => {
      suppressOverlayClickRef.current = false;
    });
  }, []);
  // React Flow 的 Handle 连线拖拽（onConnect / onReconnect 路径）走
  // @xyflow/system XYHandle 的 document 级 mousemove/mouseup，不吞随后的合成
  // click——从节点 Handle 拉线到遮罩上松手时，合成 click 命中遮罩会直接
  // onClose()，半路的新建/改目标操作与聚焦状态全丢。连线拖拽开始即武装抑制
  // 标志，结束时重新武装并在下一帧解除（与标题栏拖动/缩放手柄复用同一 ref）
  const onConnectDragStart = useCallback(() => {
    suppressOverlayClickRef.current = true;
  }, []);
  const onConnectDragEnd = useCallback(() => {
    armSuppressOverlayClick();
  }, [armSuppressOverlayClick]);

  // 悬停高亮：悬停某节点时高亮其出/入边与两端节点，其余淡出
  const [hoveredNodeId, setHoveredNodeId] = useState<string | null>(null);
  // 聚焦下钻路径（面包屑）：[] = 全图；非空 = 焦点子图，最后一项为当前焦点
  const [focusPath, setFocusPath] = useState<string[]>([]);
  // 标题栏搜索
  const [searchQuery, setSearchQuery] = useState('');
  const [searchOpen, setSearchOpen] = useState(false);

  // ---------------- T11 编辑交互状态 ----------------
  // 选中边（点击选中，Delete/右键菜单删除）
  const [selectedEdgeId, setSelectedEdgeId] = useState<string | null>(null);
  // 不可编辑边的悬停原因提示（定时器/歧义）
  const [edgeTooltip, setEdgeTooltip] = useState<{ x: number; y: number; text: string } | null>(null);
  // 边右键菜单
  const [edgeMenu, setEdgeMenu] = useState<{ x: number; y: number; edgeId: string } | null>(null);
  // 节点右键菜单（打开所在页面编辑）
  const [nodeMenu, setNodeMenu] = useState<{ x: number; y: number; nodeId: string } | null>(null);
  // 删除确认弹窗（约束 10：明示 callbacks.c 手写代码丢失）
  const [deleteConfirm, setDeleteConfirm] = useState<ViewFlowEdge | null>(null);
  // 新建跳转草稿（onConnect 拖完 → 选择器弹层）
  const [createDraft, setCreateDraft] = useState<{ sourceKey: string; targetKey: string } | null>(null);
  const [createSel, setCreateSel] = useState<{ controlId: string | null; eventType: string | null }>({ controlId: null, eventType: null });
  // round-trip 差异确认弹窗（needsConfirm 回执）
  const [rewriteConfirm, setRewriteConfirm] = useState<{ reasons: string[]; detail?: string } | null>(null);
  // 状态条（成功短暂提示 / 失败展示宿主错误）
  const [status, setStatus] = useState<{ kind: 'info' | 'success' | 'error'; text: string } | null>(null);
  const statusTimerRef = useRef<number | null>(null);
  // 最近一次写事务请求（requestId 匹配回执；needsConfirm 时凭此重发 confirmed=true）
  const lastRequestRef = useRef<{ requestId: string; message: NavEditRequestBody | null } | null>(null);
  const requestSeqRef = useRef(0);

  // 打开弹窗即请求宿主重扫导航图（allViews 常驻 store，多面板同开时会陈旧）
  // + 请求持久化布局 + 查询可撤销条数
  useEffect(() => {
    if (visible) {
      refreshNavGraph();
      requestNavLayout();
      requestNavUndoState();
    }
  }, [visible, refreshNavGraph, requestNavLayout, requestNavUndoState]);

  // 冲刷待写盘的拖动位置：取消防抖计时器并立即上报 pending patch。
  // 只发本次被拖动过的 key，宿主按 key 合并写入（不覆盖其他节点/其他面板）
  const flushLayoutSave = useCallback(() => {
    if (layoutSaveTimerRef.current !== null) {
      window.clearTimeout(layoutSaveTimerRef.current);
      layoutSaveTimerRef.current = null;
    }
    if (pendingLayoutSaveRef.current.size === 0) {
      return;
    }
    const patch = Object.fromEntries(pendingLayoutSaveRef.current);
    pendingLayoutSaveRef.current.clear();
    saveNavLayout(patch);
  }, [saveNavLayout]);

  // 关闭弹窗时复位交互态，避免下次打开残留聚焦/搜索；并把未落盘的拖动立即冲刷
  useEffect(() => {
    if (!visible) {
      setFocusPath([]);
      setHoveredNodeId(null);
      setSearchQuery('');
      setSearchOpen(false);
      flushLayoutSave();
      // 下次打开是新一轮 getNavLayout 请求-回填，避免残留上次的"已应用"标记
      appliedNavLayoutRef.current = null;
      // T11 编辑态复位（进行中的写事务回执由 requestId 匹配丢弃）
      setSelectedEdgeId(null);
      setEdgeTooltip(null);
      setEdgeMenu(null);
      setDeleteConfirm(null);
      setCreateDraft(null);
      setCreateSel({ controlId: null, eventType: null });
      setRewriteConfirm(null);
      setStatus(null);
      if (statusTimerRef.current !== null) {
        window.clearTimeout(statusTimerRef.current);
        statusTimerRef.current = null;
      }
      lastRequestRef.current = null;
      clearViewControls();
    }
  }, [visible, flushLayoutSave, clearViewControls]);

  // 防抖窗口内组件被卸载（关面板 / webview reload）→ unmount cleanup 同步冲刷，
  // 否则 800ms 内的拖动位置会静默丢失（visible→false 的冲刷路径不会跑到）
  useEffect(() => () => {
    flushLayoutSave();
  }, [flushLayoutSave]);

  const graph = useMemo(() => buildGraph(allViews, currentFilePath), [allViews, currentFilePath]);

  const seedById = useMemo(() => new Map(graph.seeds.map(s => [s.id, s])), [graph.seeds]);

  // viewKey → ViewInfo（新建跳转取源文件快照 mtime/hash）
  const viewByKey = useMemo(() => {
    const m = new Map<string, ViewInfo>();
    for (const v of allViews || []) {
      m.set(nodeIdOf(v), v);
    }
    return m;
  }, [allViews]);

  // ---------------- T11：写事务发起 / 回执处理 ----------------

  /** 状态条提示：成功/信息类可自动消隐，失败常驻直到用户关闭或被新提示覆盖 */
  const showStatus = useCallback((kind: 'info' | 'success' | 'error', text: string, autoHideMs?: number) => {
    if (statusTimerRef.current !== null) {
      window.clearTimeout(statusTimerRef.current);
      statusTimerRef.current = null;
    }
    setStatus({ kind, text });
    if (autoHideMs) {
      statusTimerRef.current = window.setTimeout(() => {
        statusTimerRef.current = null;
        setStatus(null);
      }, autoHideMs);
    }
  }, []);

  /** 发起一次写事务：生成 requestId 并记录请求（needsConfirm 重发用） */
  const sendNavEdit = useCallback((message: NavEditRequestBody) => {
    const requestId = `navEdit-${++requestSeqRef.current}-${Date.now()}`;
    lastRequestRef.current = { requestId, message };
    showStatus('info', t('Applying navigation change'));
    applyNavEdit({ requestId, ...message });
  }, [applyNavEdit, showStatus]);

  /** 撤销最近一次导航编辑（回执与写事务共用 navEditResult 通道，op='undo'） */
  const triggerUndo = useCallback(() => {
    if (navEditPending || navUndoCount === 0) {
      return;
    }
    const requestId = `navEdit-${++requestSeqRef.current}-${Date.now()}`;
    // 撤销不会走 needsConfirm 重发，message 置空（仅 requestId 用于回执匹配）
    lastRequestRef.current = { requestId, message: null };
    showStatus('info', t('Undoing last navigation change'));
    undoNavEdit(requestId);
  }, [navEditPending, navUndoCount, showStatus, undoNavEdit]);

  /** 宿主错误码 → 可读文案（dirty/过期/定位失败等各有专属提示） */
  const navEditErrorText = useCallback((errorCode?: NavEditErrorCode, errorDetail?: string): string => {
    let text: string;
    switch (errorCode) {
      case 'fileDirty': text = t('navEdit.error.fileDirty'); break;
      case 'fileChanged': text = t('navEdit.error.fileChanged'); break;
      case 'locateFailed': text = t('navEdit.error.locateFailed'); break;
      case 'fileNotFound': text = t('navEdit.error.fileNotFound'); break;
      case 'noProjectRoot': text = t('navEdit.error.noProjectRoot'); break;
      case 'invalidRequest': text = t('navEdit.error.invalidRequest'); break;
      case 'eventUnsupported': text = t('navEdit.error.eventUnsupported'); break;
      case 'eventOccupied': text = t('navEdit.error.eventOccupied'); break;
      case 'writeFailed': text = t('navEdit.error.writeFailed'); break;
      case 'rollbackFailed': text = t('navEdit.error.rollbackFailed'); break;
      case 'timerEdgeReadonly': text = t('Timer connections are read-only'); break;
      default: text = t('navEdit.error.generic'); break;
    }
    return errorDetail ? `${text} (${errorDetail})` : text;
  }, []);

  // navEditResult 回执处理：成功→关弹层+短暂提示（宿主已重扫回推 allViews 自动刷新）；
  // needsConfirm→round-trip 差异确认弹窗；失败→展示宿主错误并在图陈旧时主动重扫
  useEffect(() => {
    if (!navEditResult) {
      return;
    }
    const last = lastRequestRef.current;
    if (!visible || !last || navEditResult.requestId !== last.requestId) {
      // 非本弹窗/非本请求的回执：丢弃（弹窗关闭后到达的迟到回执也走这里）
      clearNavEditResult();
      return;
    }
    clearNavEditResult();

    if (navEditResult.success) {
      lastRequestRef.current = null;
      setDeleteConfirm(null);
      setRewriteConfirm(null);
      setCreateDraft(null);
      setCreateSel({ controlId: null, eventType: null });
      clearViewControls();
      setSelectedEdgeId(null);
      const opText = navEditResult.op === 'undo'
        ? t('Navigation change undone')
        : navEditResult.op === 'delete'
          ? t('Jump deleted')
          : navEditResult.op === 'create'
            ? t('Jump created')
            : t('Jump target updated');
      if (navEditResult.panelResyncFailed) {
        // 写盘成功但面板内存态未能重同步（评审 I1）：磁盘已正确，但该页面仍显示
        // 旧内容，用户必须手动重开，否则在该面板再保存会用旧态覆盖本次编辑。
        // 用 error 级常驻提示（不自动隐藏）以引起注意。
        showStatus('error', `${opText} · ${t('navEdit.panelResyncFailed')}`);
      } else {
        const parts = [opText, t('navEdit.codeWillRegenerate')];
        if (navEditResult.usedFileHistory) {
          // 跨文件写成功且目标文件无面板：撤销走 VS Code 文件历史
          parts.push(t('Undo via VS Code file history'));
        }
        showStatus('success', parts.join(' · '), 8000);
      }
    } else if (navEditResult.needsConfirm) {
      // 保留 lastRequestRef：用户确认后带 confirmed=true 重发
      setRewriteConfirm({
        reasons: navEditResult.confirmReasons || [],
        detail: navEditResult.confirmDetail,
      });
      setStatus(null);
    } else {
      lastRequestRef.current = null;
      setRewriteConfirm(null);
      showStatus('error', navEditErrorText(navEditResult.errorCode, navEditResult.errorDetail));
      if (navEditResult.errorCode === 'fileChanged' || navEditResult.errorCode === 'locateFailed') {
        // 图数据已陈旧：立即重扫，宿主回推后自动刷新
        refreshNavGraph();
      }
    }
  }, [navEditResult, visible, clearNavEditResult, clearViewControls, showStatus, navEditErrorText, refreshNavGraph]);

  // ---------------- T11:连接编辑回调 ----------------

  /** 占位节点不可作为连接端点（新建与改目标共用；React Flow 拖拽时实时校验） */
  const isValidConnection = useCallback((conn: ViewFlowEdge | Connection): boolean =>
    isRealViewNodeId(conn.source) && isRealViewNodeId(conn.target), []);

  /** 新建：源节点拖到目标节点 → 打开选择器弹层并请求源 view 控件列表（T9） */
  const onConnect = useCallback((connection: Connection) => {
    if (navEditPending || !isRealViewNodeId(connection.source) || !isRealViewNodeId(connection.target)) {
      return;
    }
    const src = viewByKey.get(connection.source);
    if (!src || (!src.fileHash && typeof src.fileMtime !== 'number')) {
      // 旧数据缺快照字段：写事务无法校验，重扫后再试
      showStatus('error', t('Graph data is stale, refreshing'));
      refreshNavGraph();
      return;
    }
    setCreateSel({ controlId: null, eventType: null });
    clearViewControls();
    setCreateDraft({ sourceKey: connection.source, targetKey: connection.target });
    requestViewControls(connection.source);
  }, [navEditPending, viewByKey, showStatus, refreshNavGraph, clearViewControls, requestViewControls]);

  /** 改目标：拖边目标端到另一 view 节点 → applyNavEdit(retarget) */
  const onReconnect = useCallback((oldEdge: ViewFlowEdge, connection: Connection) => {
    if (navEditPending) {
      return;
    }
    const data = oldEdge.data;
    if (!data || !data.canReconnect) {
      showStatus('error', data?.isTimer
        ? t('Timer connections are read-only')
        : data?.ambiguous
          ? t('Ambiguous connections cannot be reconnected')
          : t('This connection cannot be edited'));
      return;
    }
    if (connection.source !== oldEdge.source) {
      showStatus('error', t('Only the target end can be reconnected'));
      return;
    }
    if (!isRealViewNodeId(connection.target) || connection.target === oldEdge.target) {
      return;
    }
    const locator = locatorOf(data.raw);
    if (!locator) {
      showStatus('error', t('Graph data is stale, refreshing'));
      refreshNavGraph();
      return;
    }
    sendNavEdit({ op: 'retarget', edge: locator, newTarget: bareViewId(connection.target) });
  }, [navEditPending, showStatus, refreshNavGraph, sendNavEdit]);

  /** 删除入口（Delete 键 / 右键菜单共用）：可删则弹确认（约束 10 文案） */
  const requestDeleteEdge = useCallback((edge: ViewFlowEdge) => {
    if (navEditPending || !edge.data) {
      return;
    }
    if (edge.data.isTimer) {
      showStatus('error', t('Timer connections are read-only'));
      return;
    }
    if (!edge.data.canDelete) {
      showStatus('error', t('Graph data is stale, refreshing'));
      refreshNavGraph();
      return;
    }
    setDeleteConfirm(edge);
  }, [navEditPending, showStatus, refreshNavGraph]);

  /** 删除确认 → applyNavEdit(delete) */
  const confirmDelete = useCallback(() => {
    const edge = deleteConfirm;
    setDeleteConfirm(null);
    if (!edge?.data) {
      return;
    }
    const locator = locatorOf(edge.data.raw);
    if (!locator) {
      showStatus('error', t('Graph data is stale, refreshing'));
      refreshNavGraph();
      return;
    }
    sendNavEdit({ op: 'delete', edge: locator });
  }, [deleteConfirm, showStatus, refreshNavGraph, sendNavEdit]);

  /** 新建确认 → applyNavEdit(create)，动画用宿主默认值 */
  const confirmCreate = useCallback(() => {
    if (!createDraft || !createSel.controlId || !createSel.eventType || navEditPending) {
      return;
    }
    const src = viewByKey.get(createDraft.sourceKey);
    sendNavEdit({
      op: 'create',
      create: {
        sourceViewKey: createDraft.sourceKey,
        sourceControlId: createSel.controlId,
        eventType: createSel.eventType,
        target: bareViewId(createDraft.targetKey),
        sourceFileMtime: src?.fileMtime,
        sourceFileHash: src?.fileHash,
      },
    });
  }, [createDraft, createSel, navEditPending, viewByKey, sendNavEdit]);

  const cancelCreate = useCallback(() => {
    setCreateDraft(null);
    setCreateSel({ controlId: null, eventType: null });
    clearViewControls();
  }, [clearViewControls]);

  /** round-trip 差异确认：带 confirmed=true 重发原请求 */
  const confirmRewrite = useCallback(() => {
    const last = lastRequestRef.current;
    setRewriteConfirm(null);
    if (!last || !last.message) {
      return;
    }
    sendNavEdit({ ...last.message, confirmed: true });
  }, [sendNavEdit]);

  const cancelRewrite = useCallback(() => {
    setRewriteConfirm(null);
    lastRequestRef.current = null;
    setStatus(null);
  }, []);

  // 边选中/悬停/右键
  const onEdgeClick = useCallback((event: React.MouseEvent, edge: ViewFlowEdge) => {
    event.stopPropagation();
    setSelectedEdgeId(edge.id);
  }, []);

  const onPaneClick = useCallback(() => {
    setSelectedEdgeId(null);
    setEdgeMenu(null);
  }, []);

  const onEdgeContextMenu = useCallback((event: React.MouseEvent, edge: ViewFlowEdge) => {
    event.preventDefault();
    event.stopPropagation();
    setSelectedEdgeId(edge.id);
    setEdgeTooltip(null);
    setNodeMenu(null);
    setEdgeMenu({ x: event.clientX, y: event.clientY, edgeId: edge.id });
  }, []);

  // 节点右键：真实屏出自定义菜单（打开所在页面编辑）；占位节点只拦掉默认 Cut/Copy/Paste
  const onNodeContextMenu = useCallback((event: React.MouseEvent, node: ViewFlowNode) => {
    event.preventDefault();
    event.stopPropagation();
    setEdgeMenu(null);
    if (node.data.kind !== 'view') {
      setNodeMenu(null);
      return;
    }
    setNodeMenu({ x: event.clientX, y: event.clientY, nodeId: node.id });
  }, []);

  // 画布空白处右键：拦掉 webview 默认 Cut/Copy/Paste 菜单
  const onPaneContextMenu = useCallback((event: React.MouseEvent | MouseEvent) => {
    event.preventDefault();
    setEdgeMenu(null);
    setNodeMenu(null);
  }, []);

  const onEdgeMouseEnter = useCallback((event: React.MouseEvent, edge: ViewFlowEdge) => {
    const data = edge.data;
    if (!data) {
      return;
    }
    // 问题边悬停提示：错在哪 + 怎么修（i18n）；正常边靠标签即可，不加提示
    // expandedLabel 已含「触发控件 · 事件 · 动画」，不再重复拼控件名
    const sourceDesc = data.expandedLabel || data.shortLabel;
    const text = data.invalid
      ? t('navEdge.tooltip.invalid', data.raw?.target ?? data.targetId, sourceDesc)
      : data.ambiguous
        ? t('navEdge.tooltip.ambiguous', data.raw?.target ?? data.targetId)
        : data.isTimer
          ? t('Timer connections are read-only')
          : null;
    if (text) {
      setEdgeTooltip({ x: event.clientX, y: event.clientY, text });
    }
  }, []);

  const onEdgeMouseLeave = useCallback(() => setEdgeTooltip(null), []);

  // 右键菜单：点击任意其他位置关闭
  useEffect(() => {
    if (!edgeMenu && !nodeMenu) {
      return;
    }
    const close = () => {
      setEdgeMenu(null);
      setNodeMenu(null);
    };
    window.addEventListener('mousedown', close);
    return () => window.removeEventListener('mousedown', close);
  }, [edgeMenu, nodeMenu]);

  /** 在设计器中打开某文件并选中控件（同文件直接选中）；随后关闭弹窗进入编辑 */
  const openPageForEdit = useCallback((filePath: string | undefined, componentId: string) => {
    if (!filePath) {
      showStatus('error', t('Graph data is stale, refreshing'));
      refreshNavGraph();
      return;
    }
    if (currentFilePath && normalizePath(filePath) === normalizePath(currentFilePath)) {
      selectComponent(componentId);
    } else {
      openFileInDesigner(filePath, componentId);
    }
    onClose();
  }, [currentFilePath, selectComponent, openFileInDesigner, onClose, showStatus, refreshNavGraph]);

  // 重扫后选中边可能已消失 → 清空选中
  useEffect(() => {
    if (selectedEdgeId && !graph.edges.some(e => e.id === selectedEdgeId)) {
      setSelectedEdgeId(null);
    }
  }, [selectedEdgeId, graph.edges]);

  const anySubDialogOpen = deleteConfirm !== null || createDraft !== null || rewriteConfirm !== null;

  // 选中边按 Delete/Backspace → 删除确认（输入框内按键不拦截）
  useEffect(() => {
    if (!visible) {
      return;
    }
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== 'Delete' && e.key !== 'Backspace') {
        return;
      }
      const target = e.target as HTMLElement | null;
      if (target && (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.isContentEditable)) {
        return;
      }
      if (anySubDialogOpen || !selectedEdgeId) {
        return;
      }
      const edge = graph.edges.find(ed => ed.id === selectedEdgeId);
      if (edge) {
        e.preventDefault();
        requestDeleteEdge(edge);
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [visible, anySubDialogOpen, selectedEdgeId, graph.edges, requestDeleteEdge]);

  // 子弹窗打开时 Esc 关闭最上层子弹窗（捕获阶段拦截，避免触发聚焦返回/关弹窗）
  useEffect(() => {
    if (!visible || !anySubDialogOpen) {
      return;
    }
    const onKey = (e: KeyboardEvent) => {
      if (e.key !== 'Escape') {
        return;
      }
      e.stopPropagation();
      if (rewriteConfirm) {
        cancelRewrite();
      } else if (deleteConfirm) {
        setDeleteConfirm(null);
      } else if (createDraft) {
        cancelCreate();
      }
    };
    window.addEventListener('keydown', onKey, true);
    return () => window.removeEventListener('keydown', onKey, true);
  }, [visible, anySubDialogOpen, rewriteConfirm, deleteConfirm, createDraft, cancelRewrite, cancelCreate]);

  // 持久化布局到达 → 合并进内存位置（仅回填种子布局尚未覆盖的 key，多余 key 天然被忽略，
  // 因为 seedNodes 只按 graph.seeds 出节点）；随后重建节点应用新位置。
  useEffect(() => {
    if (!visible || !navLayout || navLayout === appliedNavLayoutRef.current) {
      return;
    }
    appliedNavLayoutRef.current = navLayout;
    let changed = false;
    for (const [key, pos] of Object.entries(navLayout)) {
      if (!positionsRef.current.has(key)) {
        positionsRef.current.set(key, pos);
        changed = true;
      }
    }
    // 聚焦模式下只合并进 positionsRef，返回全图时统一重建节点应用
    if (changed && focusPath.length === 0) {
      setNodes(seedNodes(graph.seeds, positionsRef.current));
    }
  }, [visible, navLayout, graph, focusPath]);

  const focusId = focusPath.length > 0 ? focusPath[focusPath.length - 1] : null;
  const isFocusMode = focusId !== null;
  // 无依赖回调（onNodesChange/onNodeDragStop）里读聚焦态用的镜像 ref
  const isFocusModeRef = useRef(false);
  isFocusModeRef.current = isFocusMode;

  const focusView = useMemo(() => {
    if (!focusId) {
      return null;
    }
    return buildFocusView(focusId, seedById, graph.edges);
  }, [focusId, seedById, graph.edges]);

  // 节点单一数据源：全图与聚焦子图都写进同一份受控 nodes state。
  // React Flow 的 dimensions 变更经 applyNodeChanges 回写到同一份 state，
  // 已测量尺寸得以保留——聚焦节点若另行派生传入（曾经的实现），每轮渲染的
  // 全新未测量对象会让 React Flow 无限派发测量变更（悬停刷新风暴的根因）。
  useEffect(() => {
    if (!visible) {
      return;
    }
    if (focusView) {
      setNodes(prev => {
        const measuredById = new Map(prev.map(n => [n.id, n.measured]));
        return focusView.nodes.map(n => {
          const measured = measuredById.get(n.id);
          return measured ? { ...n, measured } : n;
        });
      });
      return;
    }
    // 全图：重扫结果到达 → 重建节点（保留用户已拖动的位置）；节点集合变化时 fitView
    setNodes(seedNodes(graph.seeds, positionsRef.current));
    const sig = graph.seeds.map(s => s.id).join('|');
    if (sig !== lastSigRef.current) {
      lastSigRef.current = sig;
      window.requestAnimationFrame(() => {
        rfInstanceRef.current?.fitView({ padding: 0.15 });
      });
    }
  }, [visible, graph, focusView]);

  // 焦点节点因重扫消失（如文件被删）→ 自动回退全图，避免卡在空聚焦
  useEffect(() => {
    if (focusId && !seedById.has(focusId)) {
      setFocusPath([]);
    }
  }, [focusId, seedById]);

  // 聚焦路径变化（进入/下钻/返回）→ 重新 fitView。
  // 首次进入聚焦时节点可能尚未测量（fitView 拿不到尺寸 → 画布停在空白区），
  // 置 needsFit 标志，等 onNodesChange 的 dimensions 变更到达后补一次。
  useEffect(() => {
    if (!visible) {
      return;
    }
    needsFitRef.current = true;
    window.requestAnimationFrame(() => {
      rfInstanceRef.current?.fitView({ padding: 0.2, duration: 200 });
    });
    const timer = window.setTimeout(() => {
      needsFitRef.current = false;
    }, 800);
    return () => window.clearTimeout(timer);
  }, [visible, focusPath]);

  // 打开时居中（每次打开重新居中并退出最大化，不跨会话持久化位置）
  useEffect(() => {
    if (visible) {
      setIsMaximized(false);
      restoreRectRef.current = null;
      setDialogRect(computeDefaultDialogRect());
    }
  }, [visible]);

  // webview 面板尺寸变化时：最大化态跟随视口，否则防止已拖动的弹窗飘出可视区域
  useEffect(() => {
    if (!visible) {
      return;
    }
    const onWindowResize = () => {
      setDialogRect(prev => (isMaximized ? computeMaximizedDialogRect() : clampDialogPosition(prev)));
    };
    window.addEventListener('resize', onWindowResize);
    return () => window.removeEventListener('resize', onWindowResize);
  }, [visible, isMaximized]);

  // 调整大小 debounce 后重跑 fitView；纯拖动位置不触发（画布可视区域未变）
  useEffect(() => {
    if (!visible) {
      return;
    }
    const timer = window.setTimeout(() => {
      rfInstanceRef.current?.fitView({ padding: isFocusMode ? 0.2 : 0.15, duration: 150 });
    }, 200);
    return () => window.clearTimeout(timer);
    // 依赖有意省略 isFocusMode：聚焦切换有自己的 fitView effect，此处只响应尺寸变化
  }, [visible, dialogRect.width, dialogRect.height]);

  // 标题栏拖动：排除搜索框与工具栏按钮，避免与其内部手势冲突
  const handleHeaderPointerDown = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (e.button !== 0 || isMaximized) {
      return;
    }
    const target = e.target as HTMLElement;
    if (target.closest('.vrm-search') || target.closest('.vrm-toolbar')) {
      return;
    }
    e.preventDefault();
    const startX = e.clientX;
    const startY = e.clientY;
    const startRect = dialogRect;
    document.body.classList.add('vrm-noselect');
    setIsInteracting(true);

    const onMove = (ev: PointerEvent) => {
      setDialogRect(clampDialogPosition({
        ...startRect,
        x: startRect.x + (ev.clientX - startX),
        y: startRect.y + (ev.clientY - startY),
      }));
    };
    const onUp = () => {
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
      document.body.classList.remove('vrm-noselect');
      setIsInteracting(false);
      armSuppressOverlayClick();
    };
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);
  }, [dialogRect, armSuppressOverlayClick, isMaximized]);

  // 右下角手柄调整大小：限制最小尺寸与视口可视范围
  const handleResizePointerDown = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (e.button !== 0) {
      return;
    }
    e.preventDefault();
    e.stopPropagation();
    const startX = e.clientX;
    const startY = e.clientY;
    const startRect = dialogRect;
    document.body.classList.add('vrm-noselect');
    setIsInteracting(true);

    const onMove = (ev: PointerEvent) => {
      const maxW = Math.max(DIALOG_MIN_W, window.innerWidth - startRect.x - 8);
      const maxH = Math.max(DIALOG_MIN_H, window.innerHeight - startRect.y - 8);
      const width = Math.min(maxW, Math.max(DIALOG_MIN_W, startRect.width + (ev.clientX - startX)));
      const height = Math.min(maxH, Math.max(DIALOG_MIN_H, startRect.height + (ev.clientY - startY)));
      setDialogRect({ ...startRect, width, height });
    };
    const onUp = () => {
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
      document.body.classList.remove('vrm-noselect');
      setIsInteracting(false);
      armSuppressOverlayClick();
    };
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);
  }, [dialogRect, armSuppressOverlayClick]);

  const onNodesChange = useCallback((changes: NodeChange<ViewFlowNode>[]) => {
    setNodes(nds => applyNodeChanges(changes, nds));
    for (const change of changes) {
      // 聚焦子图内拖动只改临时展示位置，不写进全图布局（坐标系不同）
      if (change.type === 'position' && change.position && !isFocusModeRef.current) {
        positionsRef.current.set(change.id, change.position);
      }
    }
    // 进入聚焦后节点完成首次测量 → 补跑 fitView（见 focusPath 的 fitView effect）
    if (needsFitRef.current && changes.some(c => c.type === 'dimensions')) {
      needsFitRef.current = false;
      window.requestAnimationFrame(() => {
        rfInstanceRef.current?.fitView({ padding: 0.2, duration: 150 });
      });
    }
  }, []);

  const onInit = useCallback((instance: ReactFlowInstance<ViewFlowNode, ViewFlowEdge>) => {
    rfInstanceRef.current = instance;
  }, []);

  // 拖动结束（T7）：占位节点（missing/ambiguous，无真实 viewKey）不持久化；
  // 真实屏节点防抖 ~800ms 后批量上报。
  // 多选拖动时 React Flow 第三参数 nodes 是本次被拖动的全部节点，
  // 只写第二参数 node 会丢掉其余被拖节点的位置——必须全部进 patch
  const onNodeDragStop = useCallback((
    _event: MouseEvent | TouchEvent,
    node: ViewFlowNode,
    nodes: ViewFlowNode[]
  ) => {
    // 聚焦子图的临时位置不持久化（属聚焦布局坐标系，与全图布局互不相干）
    if (isFocusModeRef.current) {
      return;
    }
    const dragged = nodes && nodes.length > 0 ? nodes : [node];
    let touched = false;
    for (const n of dragged) {
      if (n.data.kind !== 'view') {
        continue;
      }
      pendingLayoutSaveRef.current.set(n.id, { x: n.position.x, y: n.position.y });
      touched = true;
    }
    if (!touched) {
      return;
    }
    if (layoutSaveTimerRef.current !== null) {
      window.clearTimeout(layoutSaveTimerRef.current);
    }
    layoutSaveTimerRef.current = window.setTimeout(() => {
      layoutSaveTimerRef.current = null;
      flushLayoutSave();
    }, LAYOUT_SAVE_DEBOUNCE_MS);
  }, [flushLayoutSave]);

  // 点击屏节点 → 进入/下钻聚焦子图；点击已聚焦节点自身忽略
  const onNodeClick = useCallback((_event: React.MouseEvent, node: ViewFlowNode) => {
    setFocusPath(prev => {
      if (prev.length > 0 && prev[prev.length - 1] === node.id) {
        return prev;
      }
      return [...prev, node.id];
    });
  }, []);

  const onNodeMouseEnter = useCallback((_event: React.MouseEvent, node: ViewFlowNode) => {
    setHoveredNodeId(node.id);
  }, []);

  const onNodeMouseLeave = useCallback(() => {
    setHoveredNodeId(null);
  }, []);

  // Esc 从聚焦子图返回全图（不关闭弹窗）；子弹窗打开时 Esc 归子弹窗（T11）
  useEffect(() => {
    if (!visible || !isFocusMode || anySubDialogOpen) {
      return;
    }
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        // 搜索框内的 Esc 归搜索框（清空搜索），捕获阶段不拦截，
        // 否则 stopPropagation 会吞掉输入框自己的 Esc 处理
        const target = e.target as HTMLElement | null;
        if (target && typeof target.closest === 'function' && target.closest('.vrm-search')) {
          return;
        }
        e.stopPropagation();
        setFocusPath([]);
      }
    };
    window.addEventListener('keydown', handleKeyDown, true);
    return () => window.removeEventListener('keydown', handleKeyDown, true);
  }, [visible, isFocusMode, anySubDialogOpen]);

  const backToOverview = useCallback(() => setFocusPath([]), []);
  const jumpToBreadcrumb = useCallback((index: number) => {
    setFocusPath(prev => prev.slice(0, index + 1));
  }, []);

  // 悬停高亮集合：当前展示图（全图或聚焦子图）中与悬停节点相连的边/节点
  const hoverSets = useMemo(() => {
    if (!hoveredNodeId) {
      return null;
    }
    const edgesForHover = isFocusMode ? (focusView?.edges || []) : graph.edges;
    const nodeIds = new Set<string>([hoveredNodeId]);
    const edgeIdSet = new Set<string>();
    for (const edge of edgesForHover) {
      if (edge.source === hoveredNodeId || edge.target === hoveredNodeId) {
        edgeIdSet.add(edge.id);
        nodeIds.add(edge.source);
        nodeIds.add(edge.target);
      }
    }
    return { nodeIds, edgeIds: edgeIdSet };
  }, [hoveredNodeId, isFocusMode, focusView, graph.edges]);

  // 节点直接用受控 state（聚焦子图节点也写进同一 state，见上方 effect）；
  // 悬停淡出经 HoverDimContext 下发到节点组件，不重建 node 对象。

  const displayEdges = useMemo(() => {
    const base = isFocusMode ? (focusView?.edges || []) : graph.edges;
    return base.map(edge => {
      const selected = edge.id === selectedEdgeId;
      const highlighted = (hoverSets ? hoverSets.edgeIds.has(edge.id) : false) || selected;
      const defaultOpacity = isFocusMode ? FOCUS_EDGE_OPACITY_DEFAULT : OVERVIEW_EDGE_OPACITY_DEFAULT;
      const fadedOpacity = isFocusMode ? FOCUS_EDGE_OPACITY_FADED : OVERVIEW_EDGE_OPACITY_FADED;
      const opacity = selected
        ? EDGE_OPACITY_HIGHLIGHT
        : hoverSets ? (highlighted ? EDGE_OPACITY_HIGHLIGHT : fadedOpacity) : defaultOpacity;
      // 聚焦模式标签常显；全图模式默认隐藏标签，悬停/选中命中才显示，避免默认满屏文字
      const labelOpacity = isFocusMode ? 1 : (highlighted ? 1 : 0);
      return {
        ...edge,
        selected,
        // 不抬 zIndex：zIndex>0 的边会渲染到节点层之上，其 ~20px 宽的不可见
        // 交互命中区会盖住悬停中的节点触发 mouseleave → 高亮取消 → mouseenter
        // 的无限振荡（悬停闪烁的根因）。高亮用透明度 + 加粗表达已足够。
        style: { ...edge.style, opacity, strokeWidth: highlighted ? 2.5 : 1.5 },
        labelStyle: { opacity: labelOpacity, fill: 'var(--vscode-foreground)', fontSize: 10 },
        labelBgStyle: { opacity: labelOpacity * 0.9 },
      };
    });
  }, [isFocusMode, focusView, graph.edges, hoverSets, selectedEdgeId]);

  const searchResults = useMemo(() => {
    const q = searchQuery.trim().toLowerCase();
    if (!q) {
      return [];
    }
    return graph.seeds
      .filter(s => s.data.kind === 'view')
      .filter(s => s.data.name.toLowerCase().includes(q) || s.data.fileLabel.toLowerCase().includes(q))
      .slice(0, 30);
  }, [searchQuery, graph.seeds]);

  const selectSearchResult = useCallback((id: string) => {
    setFocusPath([id]);
    setSearchQuery('');
    setSearchOpen(false);
  }, []);

  const onSearchKeyDown = useCallback((e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Escape') {
      setSearchQuery('');
      setSearchOpen(false);
      (e.target as HTMLInputElement).blur();
    } else if (e.key === 'Enter' && searchResults.length > 0) {
      selectSearchResult(searchResults[0].id);
    }
  }, [searchResults, selectSearchResult]);

  // ---------------- T11:渲染期派生量 ----------------

  // 新建跳转选择器：控件列表加载态（请求-响应按 viewKey 匹配）
  const controlsLoaded = createDraft !== null && viewControlsForKey === createDraft.sourceKey;
  const pickerControls = controlsLoaded && !viewControlsError ? (viewControls || []) : [];
  const selectedControl = pickerControls.find(c => c.id === createSel.controlId) || null;
  const canConfirmCreate = !!(selectedControl && createSel.eventType
    && selectedControl.supportedEvents.includes(createSel.eventType as EventType)
    && !selectedControl.occupiedSwitchViewEvents.includes(createSel.eventType as EventType));

  // 节点显示名（删除确认/选择器副标题）
  const nodeNameOf = (id: string): string => seedById.get(id)?.data.name || id;

  // 右键菜单对应的边（重扫后可能已消失）
  const menuEdge = edgeMenu ? graph.edges.find(e => e.id === edgeMenu.edgeId) || null : null;

  if (!visible) {
    return null;
  }

  return (
    <div
      className="vrm-overlay"
      onClick={e => {
        // 只响应遮罩自身的点击（冒泡自弹窗内部的不算），且拖拽/缩放刚结束的
        // 合成 click 一帧内忽略，避免拖到遮罩上释放误关弹窗（T5 回归）
        if (e.target !== e.currentTarget || suppressOverlayClickRef.current) {
          return;
        }
        onClose();
      }}
    >
      <div
        className={`vrm-dialog${isInteracting ? ' vrm-dialog-interacting' : ''}`}
        style={{ left: dialogRect.x, top: dialogRect.y, width: dialogRect.width, height: dialogRect.height }}
        onClick={e => e.stopPropagation()}
      >
        <div className="vrm-header" onPointerDown={handleHeaderPointerDown} onDoubleClick={e => {
          const target = e.target as HTMLElement;
          if (!target.closest('.vrm-search') && !target.closest('.vrm-toolbar')) {
            toggleMaximize();
          }
        }}>
          <div className="vrm-title">
            <span className="vrm-icon">🔗</span>
            {t('View Navigation Relations')}
          </div>
          <div className="vrm-search">
            <Search size={13} className="vrm-search-icon" />
            <input
              type="text"
              className="vrm-search-input"
              placeholder={t('Search views by name or file')}
              aria-label={t('Search views by name or file')}
              value={searchQuery}
              onChange={e => { setSearchQuery(e.target.value); setSearchOpen(true); }}
              onFocus={() => setSearchOpen(true)}
              onBlur={() => setSearchOpen(false)}
              onKeyDown={onSearchKeyDown}
            />
            {searchOpen && searchQuery.trim() && (
              <div className="vrm-search-results" onMouseDown={e => e.preventDefault()}>
                {searchResults.length === 0 ? (
                  <div className="vrm-search-empty">{t('No matching views')}</div>
                ) : (
                  searchResults.map(r => (
                    <div
                      key={r.id}
                      className="vrm-search-result"
                      onClick={() => selectSearchResult(r.id)}
                    >
                      <span className="vrm-search-result-name">{r.data.name}</span>
                      <span className="vrm-search-result-file">{r.data.fileLabel}</span>
                    </div>
                  ))
                )}
              </div>
            )}
          </div>
          <div className="vrm-toolbar">
            <button
              className="vrm-close"
              onClick={showHostLog}
              title={t('Open HoneyGUI log')}
              aria-label={t('Open HoneyGUI log')}
            >
              <ScrollText size={15} />
            </button>
            <button
              className="vrm-close"
              onClick={triggerUndo}
              disabled={navUndoCount === 0 || navEditPending}
              title={navUndoCount > 0 ? `${t('Undo last navigation edit')} (${navUndoCount})` : t('Nothing to undo')}
              aria-label={t('Undo last navigation edit')}
            >
              <RotateCcw size={15} />
            </button>
            <button
              className="vrm-close"
              onClick={toggleMaximize}
              title={isMaximized ? t('Restore window size') : t('Maximize')}
              aria-label={isMaximized ? t('Restore window size') : t('Maximize')}
            >
              {isMaximized ? <Minimize2 size={15} /> : <Maximize2 size={15} />}
            </button>
            <button className="vrm-close" onClick={onClose} title={t('Close')}><X size={18} /></button>
          </div>
        </div>

        {navLayoutSaveError !== null && (
          <div className="vrm-layout-save-warning" role="alert">
            <span>
              {t('Failed to save navigation layout')}
              {navLayoutSaveError ? `: ${navLayoutSaveError}` : ''}
            </span>
            <button
              className="vrm-layout-save-warning-dismiss"
              onClick={clearNavLayoutSaveError}
              title={t('Dismiss')}
              aria-label={t('Dismiss')}
            >
              <X size={12} />
            </button>
          </div>
        )}

        {status && (
          <div className={`vrm-status vrm-status-${status.kind}`} role="status">
            <span>{status.text}</span>
            <button
              className="vrm-layout-save-warning-dismiss"
              onClick={() => setStatus(null)}
              title={t('Dismiss')}
              aria-label={t('Dismiss')}
            >
              <X size={12} />
            </button>
          </div>
        )}

        <div className="vrm-canvas">
          {isFocusMode && (
            <div className="vrm-focus-bar">
              <button className="vrm-focus-back" onClick={backToOverview}>
                {`← ${t('Back to full graph')}`}
              </button>
              <div className="vrm-breadcrumb">
                {focusPath.map((id, i) => {
                  const name = seedById.get(id)?.data.name || id;
                  const isLast = i === focusPath.length - 1;
                  return (
                    <span key={id} className="vrm-breadcrumb-segment">
                      {i > 0 && <span className="vrm-breadcrumb-sep">›</span>}
                      {isLast ? (
                        <span className="vrm-breadcrumb-current">{name}</span>
                      ) : (
                        <button className="vrm-breadcrumb-link" onClick={() => jumpToBreadcrumb(i)}>{name}</button>
                      )}
                    </span>
                  );
                })}
              </div>
            </div>
          )}
          {graph.viewCount === 0 ? (
            <div className="vrm-empty">
              <div className="vrm-empty-icon">📭</div>
              <div>{t('No views')}</div>
            </div>
          ) : (
            <HoverDimContext.Provider value={hoverSets ? hoverSets.nodeIds : null}>
            <ReactFlow<ViewFlowNode, ViewFlowEdge>
              className="vrm-flow"
              nodes={nodes}
              edges={displayEdges}
              nodeTypes={nodeTypes}
              onNodesChange={onNodesChange}
              onNodeClick={onNodeClick}
              onNodeDragStop={onNodeDragStop}
              onNodeMouseEnter={onNodeMouseEnter}
              onNodeMouseLeave={onNodeMouseLeave}
              onConnect={onConnect}
              onConnectStart={onConnectDragStart}
              onConnectEnd={onConnectDragEnd}
              onReconnect={onReconnect}
              onReconnectStart={onConnectDragStart}
              onReconnectEnd={onConnectDragEnd}
              isValidConnection={isValidConnection}
              onEdgeClick={onEdgeClick}
              onEdgeContextMenu={onEdgeContextMenu}
              onNodeContextMenu={onNodeContextMenu}
              onPaneContextMenu={onPaneContextMenu}
              onEdgeMouseEnter={onEdgeMouseEnter}
              onEdgeMouseLeave={onEdgeMouseLeave}
              onPaneClick={onPaneClick}
              onInit={onInit}
              fitView
              fitViewOptions={{ padding: 0.15 }}
              minZoom={0.05}
              maxZoom={2.5}
              nodesDraggable
              nodesConnectable
              edgesReconnectable
              connectionLineStyle={{ stroke: 'var(--vscode-focusBorder)', strokeWidth: 1.5 }}
              connectionRadius={30}
              deleteKeyCode={null}
              ariaLabelConfig={{
                'controls.zoomIn.ariaLabel': t('Zoom In'),
                'controls.zoomOut.ariaLabel': t('Zoom Out'),
                'controls.fitView.ariaLabel': t('Fit to window'),
                'controls.interactive.ariaLabel': t('Toggle interactivity'),
              }}
            >
              <Background variant={BackgroundVariant.Dots} gap={24} size={1.5} />
              <MiniMap pannable zoomable nodeColor={minimapNodeColor} />
              <Controls />
            </ReactFlow>
            </HoverDimContext.Provider>
          )}
        </div>

        <div className="vrm-footer">
          <div className="vrm-legend">
            <span className="vrm-legend-item"><span className="vrm-dot vrm-dot-current" />{t('Current file')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-valid" />{t('Valid connection')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-invalid" />{t('Invalid connection')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-ambiguous" />{t('Ambiguous connection')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-timer" />{t('Timer connection')}</span>
          </div>
          <div className="vrm-stats">
            {t('Views')} {graph.viewCount} · {t('Connections')} {graph.edgeCount}
          </div>
        </div>

        {!isMaximized && (
          <div
            className="vrm-resize-handle"
            onPointerDown={handleResizePointerDown}
            title={t('Drag to resize')}
            aria-label={t('Drag to resize')}
          />
        )}

        {/* T11：删除确认（约束 10——明示 callbacks.c 手写回调将在下次代码生成时丢失） */}
        {deleteConfirm?.data && (
          <div className="vrm-subdialog-overlay">
            <div className="vrm-subdialog" role="dialog" aria-modal="true">
              <div className="vrm-subdialog-title">{t('Delete navigation jump')}</div>
              <div className="vrm-subdialog-desc">
                {nodeNameOf(deleteConfirm.source)} · {deleteConfirm.data.shortLabel} → {nodeNameOf(deleteConfirm.target)}
              </div>
              <div className="vrm-subdialog-warning">{t('Delete jump callback warning')}</div>
              <div className="vrm-subdialog-actions">
                <button className="vrm-btn" onClick={() => setDeleteConfirm(null)}>{t('common.cancel')}</button>
                <button className="vrm-btn vrm-btn-danger" disabled={navEditPending} onClick={confirmDelete}>
                  {t('Delete connection')}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* T11：新建跳转选择器（T9 getViewControls 数据：源控件 + 事件，已占事件禁用） */}
        {createDraft && (
          <div className="vrm-subdialog-overlay">
            <div className="vrm-subdialog vrm-create-dialog" role="dialog" aria-modal="true">
              <div className="vrm-subdialog-title">{t('Create navigation jump')}</div>
              <div className="vrm-subdialog-desc">
                {nodeNameOf(createDraft.sourceKey)} → {nodeNameOf(createDraft.targetKey)}
              </div>
              {!controlsLoaded ? (
                <div className="vrm-subdialog-loading">{t('Loading controls')}</div>
              ) : viewControlsError ? (
                <div className="vrm-subdialog-error">{`${t('Failed to load controls')}: ${viewControlsError}`}</div>
              ) : (
                <div className="vrm-create-body">
                  <div className="vrm-create-col">
                    <div className="vrm-create-col-title">{t('Trigger control')}</div>
                    <div className="vrm-create-list">
                      {pickerControls.length === 0 ? (
                        <div className="vrm-subdialog-empty">{t('No controls available')}</div>
                      ) : (
                        pickerControls.map(c => (
                          <button
                            key={c.id}
                            className={`vrm-create-item${createSel.controlId === c.id ? ' vrm-create-item-selected' : ''}`}
                            onClick={() => setCreateSel({ controlId: c.id, eventType: null })}
                          >
                            <span className="vrm-create-item-name">
                              {c.sourceIsView ? t('Screen itself') : (c.name || c.id)}
                            </span>
                            <span className="vrm-create-item-sub">{c.sourceIsView ? c.id : c.type}</span>
                          </button>
                        ))
                      )}
                    </div>
                  </div>
                  <div className="vrm-create-col">
                    <div className="vrm-create-col-title">{t('Trigger event')}</div>
                    <div className="vrm-create-list">
                      {!selectedControl ? (
                        <div className="vrm-subdialog-empty">{t('Select a control first')}</div>
                      ) : selectedControl.supportedEvents.length === 0 ? (
                        <div className="vrm-subdialog-empty">{t('No selectable events')}</div>
                      ) : (
                        selectedControl.supportedEvents.map(ev => {
                          const occupied = selectedControl.occupiedSwitchViewEvents.includes(ev);
                          return (
                            <button
                              key={ev}
                              disabled={occupied}
                              title={occupied ? t('Already has a jump configured') : undefined}
                              className={`vrm-create-item${createSel.eventType === ev ? ' vrm-create-item-selected' : ''}`}
                              onClick={() => setCreateSel(sel => ({ ...sel, eventType: ev }))}
                            >
                              <span className="vrm-create-item-name">{eventLabel(ev)}</span>
                              {occupied && (
                                <span className="vrm-create-item-sub">{t('Already has a jump configured')}</span>
                              )}
                            </button>
                          );
                        })
                      )}
                    </div>
                  </div>
                </div>
              )}
              <div className="vrm-subdialog-hint">{t('Default switch animation will be used')}</div>
              <div className="vrm-subdialog-actions">
                <button className="vrm-btn" onClick={cancelCreate}>{t('common.cancel')}</button>
                <button
                  className="vrm-btn vrm-btn-primary"
                  disabled={!canConfirmCreate || navEditPending}
                  onClick={confirmCreate}
                >
                  {t('common.confirm')}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* T11：round-trip 差异确认（宿主 needsConfirm 回执，确认后带 confirmed=true 重发） */}
        {rewriteConfirm && (
          <div className="vrm-subdialog-overlay">
            <div className="vrm-subdialog" role="dialog" aria-modal="true">
              <div className="vrm-subdialog-title">{t('Confirm file rewrite')}</div>
              <div className="vrm-subdialog-desc">{t('navEdit.rewriteIntro')}</div>
              <ul className="vrm-subdialog-list">
                {rewriteConfirm.reasons.map(r => (
                  <li key={r}>{rewriteReasonLabel(r)}</li>
                ))}
              </ul>
              {rewriteConfirm.detail && (
                <div className="vrm-subdialog-detail">{rewriteConfirm.detail}</div>
              )}
              <div className="vrm-subdialog-actions">
                <button className="vrm-btn" onClick={cancelRewrite}>{t('common.cancel')}</button>
                <button className="vrm-btn vrm-btn-primary" disabled={navEditPending} onClick={confirmRewrite}>
                  {t('Continue')}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* T11：边右键菜单（打开源控件所在页面 / 删除；定时器边删除禁用并注明原因） */}
        {edgeMenu && menuEdge?.data && (
          <div
            className="vrm-edge-menu"
            style={{ left: edgeMenu.x, top: edgeMenu.y }}
            onMouseDown={e => e.stopPropagation()}
          >
            <button
              className="vrm-edge-menu-item"
              onClick={() => {
                setEdgeMenu(null);
                const raw = menuEdge.data!.raw;
                // 旧数据可能缺 sourceControlId：仍打开页面，只是不预选控件
                openPageForEdit(raw.sourceFilePath, raw.sourceControlId ?? '');
              }}
            >
              {t('Open the source control\'s page in the designer')}
            </button>
            <button
              className="vrm-edge-menu-item"
              disabled={menuEdge.data.isTimer || !menuEdge.data.canDelete}
              title={menuEdge.data.isTimer
                ? t('Timer connections are read-only')
                : !menuEdge.data.canDelete
                  ? t('This connection cannot be edited')
                  : undefined}
              onClick={() => {
                setEdgeMenu(null);
                requestDeleteEdge(menuEdge);
              }}
            >
              {t('Delete connection')}
            </button>
          </div>
        )}

        {/* 节点右键菜单：打开该页面编辑 */}
        {nodeMenu && (
          <div
            className="vrm-edge-menu"
            style={{ left: nodeMenu.x, top: nodeMenu.y }}
            onMouseDown={e => e.stopPropagation()}
          >
            <button
              className="vrm-edge-menu-item"
              onClick={() => {
                const id = nodeMenu.nodeId;
                setNodeMenu(null);
                const view = viewByKey.get(id);
                openPageForEdit(view?.filePath, view?.id ?? id);
              }}
            >
              {t('Open this page in the designer')}
            </button>
          </div>
        )}

        {/* T11：不可编辑边的悬停原因提示 */}
        {edgeTooltip && !edgeMenu && (
          <div className="vrm-edge-tooltip" style={{ left: edgeTooltip.x + 12, top: edgeTooltip.y + 14 }}>
            {edgeTooltip.text}
          </div>
        )}
      </div>
    </div>
  );
};
