import React, { useMemo, useRef, useState, useEffect, useCallback } from 'react';
import { X, Search } from 'lucide-react';
import {
  ReactFlow,
  MiniMap,
  Controls,
  Background,
  BackgroundVariant,
  MarkerType,
  Position,
  Handle,
  applyNodeChanges,
  type Node,
  type Edge,
  type NodeChange,
  type NodeProps,
  type ReactFlowInstance,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useDesignerStore } from '../store';
import { t } from '../i18n';
import type { ViewInfo, ViewEdgeInfo } from '../types';
import { SWITCH_OUT_STYLES, SWITCH_IN_STYLES } from '../../hml/eventTypes';
import './ViewRelationModal.css';

interface ViewRelationModalProps {
  visible: boolean;
  onClose: () => void;
}

// 配色统一走主题变量（局部变量在 ViewRelationModal.css 的 .vrm-overlay 上定义，
// 由 --vscode-charts-* 派生并带回退链；禁止硬编码颜色）
const COLOR_VALID = 'var(--vrm-color-valid)';
const COLOR_INVALID = 'var(--vrm-color-invalid)';
const COLOR_AMBIGUOUS = 'var(--vrm-color-ambiguous)';
const COLOR_CURRENT = 'var(--vscode-focusBorder)';
const COLOR_NODE_DEFAULT = 'var(--vscode-editorWidget-border, var(--vscode-panel-border))';

// 默认淡出/正常/高亮透明度（全局图默认低透明度，悬停高亮相关边）
const OVERVIEW_EDGE_OPACITY_DEFAULT = 0.1;
const OVERVIEW_EDGE_OPACITY_FADED = 0.04;
const FOCUS_EDGE_OPACITY_DEFAULT = 0.85;
const FOCUS_EDGE_OPACITY_FADED = 0.3;
const EDGE_OPACITY_HIGHLIGHT = 1;

// 节点拖动结束后的布局写盘防抖间隔（T7）
const LAYOUT_SAVE_DEBOUNCE_MS = 800;

// ---------------- 节点数据模型 ----------------

type ViewNodeKind = 'view' | 'missing' | 'ambiguous';

interface ViewNodeData extends Record<string, unknown> {
  name: string;
  fileLabel: string;      // 文件相对路径（T2 fileRelative；旧数据回退 basename）
  isCurrentFile: boolean;
  kind: ViewNodeKind;     // view=真实屏；missing=无效目标占位；ambiguous=歧义目标占位
  invalidOut: number;     // 出边中无效目标条数
  ambiguousOut: number;   // 出边中歧义目标条数
  autoId: boolean;        // id 为解析器自动生成（建议补显式 id）
  dimmed?: boolean;       // 悬停淡出态（渲染期计算，不入 state）
}

type ViewFlowNode = Node<ViewNodeData, 'viewCard'>;

// ---------------- 边数据模型 ----------------

interface ViewEdgeData extends Record<string, unknown> {
  sourceId: string;
  targetId: string;
  isTimer: boolean;
  invalid: boolean;
  ambiguous: boolean;
  shortLabel: string;    // 全局图标签：触发控件 · 手势
  expandedLabel: string; // 聚焦模式标签：触发控件 · 事件 · 动画
}

type ViewFlowEdge = Edge<ViewEdgeData>;

// ---------------- 工具函数 ----------------

/** 路径规范化比较（统一正斜杠 + 忽略大小写，Windows 盘符/分隔符差异不敏感） */
const normalizePath = (p: string): string => p.replace(/\\/g, '/').toLowerCase();

/** 节点 id：viewKey 复合键（relPath#viewId）；旧数据回退 file#id */
const nodeIdOf = (view: ViewInfo): string => view.viewKey || `${view.file}#${view.id}`;

/** 解析器确定性 fallback id 形如 `${basename}_hg_view_auto_N` / `hg_view_auto_N` */
const isAutoGeneratedId = (id: string): boolean => /(^|_)hg_view_auto_\d+$/.test(id);

/** 事件类型 → 本地化标签（复用 event.* i18n key，缺失回退原始值） */
const eventLabel = (type: string): string => {
  const key = `event.${type}`;
  const label = t(key as Parameters<typeof t>[0]);
  return label === key ? type : label;
};

const SWITCH_OUT_DEFAULT = 'SWITCH_OUT_TO_LEFT_USE_TRANSLATION';
const SWITCH_IN_DEFAULT = 'SWITCH_IN_FROM_RIGHT_USE_TRANSLATION';

/** 切换动画枚举值 → 本地化标签（缺失回退默认动画） */
const styleLabel = (
  list: { value: string; labelKey: string }[],
  value: string | undefined,
  fallback: string
): string => {
  const v = value || fallback;
  const found = list.find(s => s.value === v);
  return found ? t(found.labelKey as Parameters<typeof t>[0]) : v;
};

/** 出/入动画组合标签，用于聚焦模式展开的 `触发控件·事件·动画` */
const animationLabelOf = (e: ViewEdgeInfo): string => {
  const out = styleLabel(SWITCH_OUT_STYLES, e.switchOutStyle, SWITCH_OUT_DEFAULT);
  const inn = styleLabel(SWITCH_IN_STYLES, e.switchInStyle, SWITCH_IN_DEFAULT);
  return `${out} → ${inn}`;
};

// ---------------- 自定义节点：屏卡片 ----------------

const ViewCardNode: React.FC<NodeProps<ViewFlowNode>> = ({ data }) => {
  const classes = ['vrm-node', `vrm-node-${data.kind}`];
  if (data.isCurrentFile) {
    classes.push('vrm-node-current');
  }
  if (data.dimmed) {
    classes.push('vrm-node-dimmed');
  }
  const hasBadges = data.invalidOut > 0 || data.ambiguousOut > 0 || data.autoId;
  return (
    <div className={classes.join(' ')}>
      <Handle type="target" position={Position.Left} className="vrm-handle" isConnectable={false} />
      <div className="vrm-node-name" title={data.name}>
        {data.isCurrentFile && <span className="vrm-node-star">★</span>}
        <span className="vrm-node-name-text">{data.name}</span>
      </div>
      <div className="vrm-node-file" title={data.fileLabel}>
        {data.kind === 'view'
          ? data.fileLabel
          : data.kind === 'missing'
            ? t('Target not found')
            : t('Ambiguous target')}
      </div>
      {hasBadges && (
        <div className="vrm-node-badges">
          {data.invalidOut > 0 && (
            <span className="vrm-badge vrm-badge-invalid" title={t('Has invalid jump target')}>
              ⚠ {data.invalidOut}
            </span>
          )}
          {data.ambiguousOut > 0 && (
            <span className="vrm-badge vrm-badge-ambiguous" title={t('Has ambiguous jump target')}>
              ⚠ {data.ambiguousOut}
            </span>
          )}
          {data.autoId && (
            <span className="vrm-badge vrm-badge-autoid" title={t('View has no id, consider adding one')}>
              id?
            </span>
          )}
        </div>
      )}
      <Handle type="source" position={Position.Right} className="vrm-handle" isConnectable={false} />
    </div>
  );
};

const nodeTypes = { viewCard: ViewCardNode };

// ---------------- 图构建 ----------------

interface GraphSeed {
  id: string;
  data: ViewNodeData;
}

interface GraphModel {
  seeds: GraphSeed[]; // 已按种子布局顺序排序（当前文件优先 → 相对路径 → 名称；占位节点殿后）
  edges: ViewFlowEdge[];
  viewCount: number;
  edgeCount: number;
}

const buildGraph = (allViews: ViewInfo[] | undefined, currentFilePath: string | undefined): GraphModel => {
  const views = allViews || [];
  const cur = currentFilePath ? normalizePath(currentFilePath) : '';

  const isCurrentFile = (v: ViewInfo): boolean => {
    if (!cur) {
      return false;
    }
    if (v.filePath) {
      return normalizePath(v.filePath) === cur;
    }
    // 旧数据无绝对路径：回退 basename 比较
    const base = (cur.split('/').pop() || '').replace(/\.hml$/, '');
    return base !== '' && base === v.file.toLowerCase();
  };

  const fileLabelOf = (v: ViewInfo): string => v.fileRelative || v.file;

  // 种子布局排序：当前文件优先 → 相对路径 → 名称
  const ordered = [...views].sort((a, b) => {
    const aCur = isCurrentFile(a);
    const bCur = isCurrentFile(b);
    if (aCur !== bCur) {
      return aCur ? -1 : 1;
    }
    const fileCmp = fileLabelOf(a).localeCompare(fileLabelOf(b));
    if (fileCmp !== 0) {
      return fileCmp;
    }
    return a.name.localeCompare(b.name);
  });

  const edges: ViewFlowEdge[] = [];
  const edgeIds = new Set<string>();
  // 占位节点：无效 / 歧义目标（保证每条 T2 边都可见）
  const synthetic = new Map<string, GraphSeed>();
  const invalidOutBy = new Map<string, number>();
  const ambiguousOutBy = new Map<string, number>();
  const seenNodeIds = new Set<string>();
  const seeds: GraphSeed[] = [];

  for (const view of ordered) {
    const id = nodeIdOf(view);
    if (seenNodeIds.has(id)) {
      continue; // 防御：复合键理论上唯一
    }
    seenNodeIds.add(id);
    seeds.push({
      id,
      data: {
        name: view.name,
        fileLabel: fileLabelOf(view),
        isCurrentFile: isCurrentFile(view),
        kind: 'view',
        invalidOut: 0,
        ambiguousOut: 0,
        autoId: isAutoGeneratedId(view.id),
      },
    });
  }

  for (const view of ordered) {
    const sourceId = nodeIdOf(view);
    (view.edges || []).forEach((e, ei) => {
      if (!e.target) {
        return;
      }
      const isTimer = e.sourceIsTimer === true || (e.eventType || e.event) === 'timer';
      const invalid = e.isValid === false;
      const ambiguous = e.targetAmbiguous === true;

      let targetNodeId: string;
      if (invalid) {
        targetNodeId = `missing:${e.target}`;
        invalidOutBy.set(sourceId, (invalidOutBy.get(sourceId) || 0) + 1);
      } else if (ambiguous || !e.targetViewKey) {
        // 歧义（或旧数据未解析出目标复合键）→ 歧义占位节点
        targetNodeId = `ambiguous:${e.target}`;
        ambiguousOutBy.set(sourceId, (ambiguousOutBy.get(sourceId) || 0) + 1);
      } else {
        targetNodeId = e.targetViewKey;
      }

      if (targetNodeId.startsWith('missing:') || targetNodeId.startsWith('ambiguous:')) {
        if (!synthetic.has(targetNodeId)) {
          synthetic.set(targetNodeId, {
            id: targetNodeId,
            data: {
              name: e.target,
              fileLabel: '',
              isCurrentFile: false,
              kind: targetNodeId.startsWith('missing:') ? 'missing' : 'ambiguous',
              invalidOut: 0,
              ambiguousOut: 0,
              autoId: false,
            },
          });
        }
      }

      // 边标签：触发控件 · 手势（定时器边标注"定时器触发"）；聚焦模式再拼接动画
      const controlPart = e.sourceIsView
        ? t('Screen')
        : (e.sourceControlName || e.sourceControlId || '');
      const triggerPart = isTimer ? t('Timer trigger') : eventLabel(e.eventType || e.event);
      const shortLabel = controlPart ? `${controlPart} · ${triggerPart}` : triggerPart;
      const expandedLabel = `${shortLabel} · ${animationLabelOf(e)}`;

      const color = invalid ? COLOR_INVALID : ambiguous ? COLOR_AMBIGUOUS : COLOR_VALID;
      let edgeId = e.edgeId || `${sourceId}->${e.target}@${ei}`;
      if (edgeIds.has(edgeId)) {
        edgeId = `${edgeId}@${ei}`;
      }
      edgeIds.add(edgeId);

      const classNames = ['vrm-edge'];
      if (invalid) {
        classNames.push('vrm-edge-invalid');
      } else if (ambiguous) {
        classNames.push('vrm-edge-ambiguous');
      }
      if (isTimer) {
        classNames.push('vrm-edge-timer');
      }

      edges.push({
        id: edgeId,
        source: sourceId,
        target: targetNodeId,
        label: shortLabel,
        className: classNames.join(' '),
        style: {
          stroke: color,
          strokeWidth: 1.5,
          opacity: OVERVIEW_EDGE_OPACITY_DEFAULT,
          ...(isTimer ? { strokeDasharray: '6 4' } : {}),
        },
        markerEnd: { type: MarkerType.ArrowClosed, color, width: 16, height: 16 },
        data: {
          sourceId,
          targetId: targetNodeId,
          isTimer,
          invalid,
          ambiguous,
          shortLabel,
          expandedLabel,
        },
      });
    });
  }

  // 回填出边告警计数
  for (const seed of seeds) {
    seed.data.invalidOut = invalidOutBy.get(seed.id) || 0;
    seed.data.ambiguousOut = ambiguousOutBy.get(seed.id) || 0;
  }

  // 占位节点殿后，按名称排序
  const syntheticSeeds = [...synthetic.values()].sort((a, b) => a.data.name.localeCompare(b.data.name));

  return {
    seeds: [...seeds, ...syntheticSeeds],
    edges,
    viewCount: views.length,
    edgeCount: edges.length,
  };
};

// 种子网格布局：≈√(1.6n) 列的紧凑网格（同文件 view 因排序相邻聚拢）
const GRID_CELL_W = 260;
const GRID_CELL_H = 130;

// 聚焦子图布局：左入右出（前驱居左，焦点居中，后继居右）
const FOCUS_COL_GAP = 340;
const FOCUS_ROW_GAP = 120;

const seedNodes = (
  seeds: GraphSeed[],
  savedPositions: Map<string, { x: number; y: number }>
): ViewFlowNode[] => {
  const cols = Math.max(1, Math.round(Math.sqrt(seeds.length * 1.6)));
  return seeds.map((seed, i) => ({
    id: seed.id,
    type: 'viewCard' as const,
    position: savedPositions.get(seed.id) || {
      x: (i % cols) * GRID_CELL_W,
      y: Math.floor(i / cols) * GRID_CELL_H,
    },
    data: seed.data,
  }));
};

const minimapNodeColor = (node: Node): string => {
  const data = node.data as ViewNodeData | undefined;
  if (data?.kind === 'missing') {
    return COLOR_INVALID;
  }
  if (data?.kind === 'ambiguous') {
    return COLOR_AMBIGUOUS;
  }
  if (data?.isCurrentFile) {
    return COLOR_CURRENT;
  }
  return COLOR_NODE_DEFAULT;
};

interface FocusView {
  nodes: ViewFlowNode[];
  edges: ViewFlowEdge[];
}

/** 焦点 + 直接前驱 + 直接后继 子图，左入右出布局 */
const buildFocusView = (
  focusId: string,
  seedById: Map<string, GraphSeed>,
  allEdges: ViewFlowEdge[]
): FocusView | null => {
  const focusSeed = seedById.get(focusId);
  if (!focusSeed) {
    return null;
  }

  const predecessorIds: string[] = [];
  const successorIds: string[] = [];
  const seenPred = new Set<string>();
  const seenSucc = new Set<string>();
  const relatedEdges = new Map<string, ViewFlowEdge>();

  for (const edge of allEdges) {
    const isIncoming = edge.target === focusId;
    const isOutgoing = edge.source === focusId;
    if (!isIncoming && !isOutgoing) {
      continue;
    }
    relatedEdges.set(edge.id, edge);
    if (isIncoming && edge.source !== focusId && !seenPred.has(edge.source)) {
      seenPred.add(edge.source);
      predecessorIds.push(edge.source);
    }
    if (isOutgoing && edge.target !== focusId && !seenSucc.has(edge.target)) {
      seenSucc.add(edge.target);
      successorIds.push(edge.target);
    }
  }

  const nodes: ViewFlowNode[] = [];
  predecessorIds.forEach((id, i) => {
    const seed = seedById.get(id);
    if (!seed) {
      return;
    }
    nodes.push({ id, type: 'viewCard', position: { x: 0, y: i * FOCUS_ROW_GAP }, data: seed.data });
  });

  const centerRowCount = Math.max(predecessorIds.length, successorIds.length, 1);
  nodes.push({
    id: focusId,
    type: 'viewCard',
    position: { x: FOCUS_COL_GAP, y: ((centerRowCount - 1) * FOCUS_ROW_GAP) / 2 },
    data: focusSeed.data,
  });

  successorIds.forEach((id, i) => {
    const seed = seedById.get(id);
    if (!seed) {
      return;
    }
    nodes.push({ id, type: 'viewCard', position: { x: FOCUS_COL_GAP * 2, y: i * FOCUS_ROW_GAP }, data: seed.data });
  });

  const edges: ViewFlowEdge[] = [...relatedEdges.values()].map(edge => ({
    ...edge,
    label: edge.data?.expandedLabel ?? edge.label,
  }));

  return { nodes, edges };
};

// ---------------- 弹窗:可拖拽 + 可调大小(T5) ----------------

interface DialogRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

const DIALOG_MIN_W = 640;
const DIALOG_MIN_H = 420;
const DIALOG_DEFAULT_MAX_W = 1200;
const DIALOG_DEFAULT_MAX_H = 820;
const DIALOG_VIEWPORT_RATIO_W = 0.9;
const DIALOG_VIEWPORT_RATIO_H = 0.88;

/** 打开时居中的默认尺寸：min(1200px,90vw) × min(820px,88vh)，不低于最小尺寸 */
const computeDefaultDialogRect = (): DialogRect => {
  const width = Math.max(DIALOG_MIN_W, Math.min(DIALOG_DEFAULT_MAX_W, window.innerWidth * DIALOG_VIEWPORT_RATIO_W));
  const height = Math.max(DIALOG_MIN_H, Math.min(DIALOG_DEFAULT_MAX_H, window.innerHeight * DIALOG_VIEWPORT_RATIO_H));
  return {
    width,
    height,
    x: Math.max(0, (window.innerWidth - width) / 2),
    y: Math.max(0, (window.innerHeight - height) / 2),
  };
};

/** 拖动后限制标题栏至少部分可见，避免弹窗整体飘出可视区域 */
const clampDialogPosition = (rect: DialogRect): DialogRect => {
  const minVisible = 160;
  const minX = -(rect.width - minVisible);
  const maxX = window.innerWidth - minVisible;
  const minY = 0;
  const maxY = Math.max(0, window.innerHeight - 48);
  return {
    ...rect,
    x: Math.min(maxX, Math.max(minX, rect.x)),
    y: Math.min(maxY, Math.max(minY, rect.y)),
  };
};

// ---------------- 弹窗组件 ----------------

export const ViewRelationModal: React.FC<ViewRelationModalProps> = ({ visible, onClose }) => {
  const allViews = useDesignerStore(s => s.allViews);
  const currentFilePath = useDesignerStore(s => s.currentFilePath);
  const refreshNavGraph = useDesignerStore(s => s.refreshNavGraph);
  // 节点布局持久化（T7）：宿主读回 <projectRoot>/.honeygui/nav-layout.json
  const navLayout = useDesignerStore(s => s.navLayout);
  const requestNavLayout = useDesignerStore(s => s.requestNavLayout);
  const saveNavLayout = useDesignerStore(s => s.saveNavLayout);
  const navLayoutSaveError = useDesignerStore(s => s.navLayoutSaveError);
  const clearNavLayoutSaveError = useDesignerStore(s => s.clearNavLayoutSaveError);

  const [nodes, setNodes] = useState<ViewFlowNode[]>([]);
  // 拖动位置暂存（组件内存态；已加载的持久化布局在到达时合并进来，未知 key 回退种子布局）
  const positionsRef = useRef(new Map<string, { x: number; y: number }>());
  const rfInstanceRef = useRef<ReactFlowInstance<ViewFlowNode, ViewFlowEdge> | null>(null);
  const lastSigRef = useRef('');
  // T7：已应用过的持久化布局对象引用，避免同一份 navLayout 重复合并
  const appliedNavLayoutRef = useRef<Record<string, { x: number; y: number }> | null>(null);
  // T7：拖动结束后待写盘的 key（防抖聚合，只上报被拖动过的节点）
  const pendingLayoutSaveRef = useRef(new Map<string, { x: number; y: number }>());
  const layoutSaveTimerRef = useRef<number | null>(null);

  // 弹窗可拖拽 + 可调大小（T5）：受控 position/size，打开时居中
  const [dialogRect, setDialogRect] = useState<DialogRect>(() => computeDefaultDialogRect());
  // 拖动/调整大小进行中：禁用文本选中、隔离图层 pan/zoom 手势
  const [isInteracting, setIsInteracting] = useState(false);

  // 悬停高亮：悬停某节点时高亮其出/入边与两端节点，其余淡出
  const [hoveredNodeId, setHoveredNodeId] = useState<string | null>(null);
  // 聚焦下钻路径（面包屑）：[] = 全图；非空 = 焦点子图，最后一项为当前焦点
  const [focusPath, setFocusPath] = useState<string[]>([]);
  // 标题栏搜索
  const [searchQuery, setSearchQuery] = useState('');
  const [searchOpen, setSearchOpen] = useState(false);

  // 打开弹窗即请求宿主重扫导航图（allViews 常驻 store，多面板同开时会陈旧）+ 请求持久化布局
  useEffect(() => {
    if (visible) {
      refreshNavGraph();
      requestNavLayout();
    }
  }, [visible, refreshNavGraph, requestNavLayout]);

  // 关闭弹窗时复位交互态，避免下次打开残留聚焦/搜索；并把未落盘的拖动立即冲刷
  useEffect(() => {
    if (!visible) {
      setFocusPath([]);
      setHoveredNodeId(null);
      setSearchQuery('');
      setSearchOpen(false);
      if (layoutSaveTimerRef.current !== null) {
        window.clearTimeout(layoutSaveTimerRef.current);
        layoutSaveTimerRef.current = null;
        if (pendingLayoutSaveRef.current.size > 0) {
          const patch = Object.fromEntries(pendingLayoutSaveRef.current);
          pendingLayoutSaveRef.current.clear();
          saveNavLayout(patch);
        }
      }
      // 下次打开是新一轮 getNavLayout 请求-回填，避免残留上次的"已应用"标记
      appliedNavLayoutRef.current = null;
    }
  }, [visible, saveNavLayout]);

  const graph = useMemo(() => buildGraph(allViews, currentFilePath), [allViews, currentFilePath]);

  const seedById = useMemo(() => new Map(graph.seeds.map(s => [s.id, s])), [graph.seeds]);

  // 持久化布局到达 → 合并进内存位置（仅回填种子布局尚未覆盖的 key，多余 key 天然被忽略，
  // 因为 seedNodes 只按 graph.seeds 出节点）；随后重建节点应用新位置。
  useEffect(() => {
    if (!visible || !navLayout || navLayout === appliedNavLayoutRef.current) {
      return;
    }
    appliedNavLayoutRef.current = navLayout;
    let changed = false;
    for (const [key, pos] of Object.entries(navLayout)) {
      if (!positionsRef.current.has(key)) {
        positionsRef.current.set(key, pos);
        changed = true;
      }
    }
    if (changed) {
      setNodes(seedNodes(graph.seeds, positionsRef.current));
    }
  }, [visible, navLayout, graph]);

  // 打开期间重扫结果到达 → 重建节点（保留用户已拖动的位置）；
  // 节点集合变化时重新 fitView
  useEffect(() => {
    if (!visible) {
      return;
    }
    setNodes(seedNodes(graph.seeds, positionsRef.current));
    const sig = graph.seeds.map(s => s.id).join('|');
    if (sig !== lastSigRef.current) {
      lastSigRef.current = sig;
      window.requestAnimationFrame(() => {
        rfInstanceRef.current?.fitView({ padding: 0.15 });
      });
    }
  }, [visible, graph]);

  const focusId = focusPath.length > 0 ? focusPath[focusPath.length - 1] : null;
  const isFocusMode = focusId !== null;

  const focusView = useMemo(() => {
    if (!focusId) {
      return null;
    }
    return buildFocusView(focusId, seedById, graph.edges);
  }, [focusId, seedById, graph.edges]);

  // 焦点节点因重扫消失（如文件被删）→ 自动回退全图，避免卡在空聚焦
  useEffect(() => {
    if (focusId && !seedById.has(focusId)) {
      setFocusPath([]);
    }
  }, [focusId, seedById]);

  // 聚焦路径变化（进入/下钻/返回）→ 重新 fitView
  useEffect(() => {
    if (!visible) {
      return;
    }
    window.requestAnimationFrame(() => {
      rfInstanceRef.current?.fitView({ padding: 0.2, duration: 200 });
    });
  }, [visible, focusPath]);

  // 打开时居中，尺寸默认 min(1200,90vw) × min(820,88vh)（每次打开重新居中，不跨会话持久化位置）
  useEffect(() => {
    if (visible) {
      setDialogRect(computeDefaultDialogRect());
    }
  }, [visible]);

  // webview 面板尺寸变化时，防止已拖动的弹窗整体飘出可视区域
  useEffect(() => {
    if (!visible) {
      return;
    }
    const onWindowResize = () => setDialogRect(prev => clampDialogPosition(prev));
    window.addEventListener('resize', onWindowResize);
    return () => window.removeEventListener('resize', onWindowResize);
  }, [visible]);

  // 调整大小 debounce 后重跑 fitView；纯拖动位置不触发（画布可视区域未变）
  useEffect(() => {
    if (!visible) {
      return;
    }
    const timer = window.setTimeout(() => {
      rfInstanceRef.current?.fitView({ padding: isFocusMode ? 0.2 : 0.15, duration: 150 });
    }, 200);
    return () => window.clearTimeout(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [visible, dialogRect.width, dialogRect.height]);

  // 标题栏拖动：排除搜索框与工具栏按钮，避免与其内部手势冲突
  const handleHeaderPointerDown = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (e.button !== 0) {
      return;
    }
    const target = e.target as HTMLElement;
    if (target.closest('.vrm-search') || target.closest('.vrm-toolbar')) {
      return;
    }
    e.preventDefault();
    const startX = e.clientX;
    const startY = e.clientY;
    const startRect = dialogRect;
    document.body.classList.add('vrm-noselect');
    setIsInteracting(true);

    const onMove = (ev: PointerEvent) => {
      setDialogRect(clampDialogPosition({
        ...startRect,
        x: startRect.x + (ev.clientX - startX),
        y: startRect.y + (ev.clientY - startY),
      }));
    };
    const onUp = () => {
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
      document.body.classList.remove('vrm-noselect');
      setIsInteracting(false);
    };
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);
  }, [dialogRect]);

  // 右下角手柄调整大小：限制最小尺寸与视口可视范围
  const handleResizePointerDown = useCallback((e: React.PointerEvent<HTMLDivElement>) => {
    if (e.button !== 0) {
      return;
    }
    e.preventDefault();
    e.stopPropagation();
    const startX = e.clientX;
    const startY = e.clientY;
    const startRect = dialogRect;
    document.body.classList.add('vrm-noselect');
    setIsInteracting(true);

    const onMove = (ev: PointerEvent) => {
      const maxW = Math.max(DIALOG_MIN_W, window.innerWidth - startRect.x - 8);
      const maxH = Math.max(DIALOG_MIN_H, window.innerHeight - startRect.y - 8);
      const width = Math.min(maxW, Math.max(DIALOG_MIN_W, startRect.width + (ev.clientX - startX)));
      const height = Math.min(maxH, Math.max(DIALOG_MIN_H, startRect.height + (ev.clientY - startY)));
      setDialogRect({ ...startRect, width, height });
    };
    const onUp = () => {
      window.removeEventListener('pointermove', onMove);
      window.removeEventListener('pointerup', onUp);
      document.body.classList.remove('vrm-noselect');
      setIsInteracting(false);
    };
    window.addEventListener('pointermove', onMove);
    window.addEventListener('pointerup', onUp);
  }, [dialogRect]);

  const onNodesChange = useCallback((changes: NodeChange<ViewFlowNode>[]) => {
    setNodes(nds => applyNodeChanges(changes, nds));
    for (const change of changes) {
      if (change.type === 'position' && change.position) {
        positionsRef.current.set(change.id, change.position);
      }
    }
  }, []);

  const onInit = useCallback((instance: ReactFlowInstance<ViewFlowNode, ViewFlowEdge>) => {
    rfInstanceRef.current = instance;
  }, []);

  // 冲刷待写盘的拖动位置：只发本次被拖动过的 key，宿主按 key 合并写入（不覆盖其他节点/其他面板）
  const flushLayoutSave = useCallback(() => {
    if (pendingLayoutSaveRef.current.size === 0) {
      return;
    }
    const patch = Object.fromEntries(pendingLayoutSaveRef.current);
    pendingLayoutSaveRef.current.clear();
    saveNavLayout(patch);
  }, [saveNavLayout]);

  // 拖动结束（T7）：占位节点（missing/ambiguous，无真实 viewKey）不持久化；
  // 真实屏节点防抖 ~800ms 后批量上报
  const onNodeDragStop = useCallback((_event: MouseEvent | TouchEvent, node: ViewFlowNode) => {
    if (node.data.kind !== 'view') {
      return;
    }
    pendingLayoutSaveRef.current.set(node.id, { x: node.position.x, y: node.position.y });
    if (layoutSaveTimerRef.current !== null) {
      window.clearTimeout(layoutSaveTimerRef.current);
    }
    layoutSaveTimerRef.current = window.setTimeout(() => {
      layoutSaveTimerRef.current = null;
      flushLayoutSave();
    }, LAYOUT_SAVE_DEBOUNCE_MS);
  }, [flushLayoutSave]);

  // 点击屏节点 → 进入/下钻聚焦子图；点击已聚焦节点自身忽略
  const onNodeClick = useCallback((_event: React.MouseEvent, node: ViewFlowNode) => {
    setFocusPath(prev => {
      if (prev.length > 0 && prev[prev.length - 1] === node.id) {
        return prev;
      }
      return [...prev, node.id];
    });
  }, []);

  const onNodeMouseEnter = useCallback((_event: React.MouseEvent, node: ViewFlowNode) => {
    setHoveredNodeId(node.id);
  }, []);

  const onNodeMouseLeave = useCallback(() => {
    setHoveredNodeId(null);
  }, []);

  // Esc 从聚焦子图返回全图（不关闭弹窗）
  useEffect(() => {
    if (!visible || !isFocusMode) {
      return;
    }
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.stopPropagation();
        setFocusPath([]);
      }
    };
    window.addEventListener('keydown', handleKeyDown, true);
    return () => window.removeEventListener('keydown', handleKeyDown, true);
  }, [visible, isFocusMode]);

  const backToOverview = useCallback(() => setFocusPath([]), []);
  const jumpToBreadcrumb = useCallback((index: number) => {
    setFocusPath(prev => prev.slice(0, index + 1));
  }, []);

  // 悬停高亮集合：当前展示图（全图或聚焦子图）中与悬停节点相连的边/节点
  const hoverSets = useMemo(() => {
    if (!hoveredNodeId) {
      return null;
    }
    const edgesForHover = isFocusMode ? (focusView?.edges || []) : graph.edges;
    const nodeIds = new Set<string>([hoveredNodeId]);
    const edgeIdSet = new Set<string>();
    for (const edge of edgesForHover) {
      if (edge.source === hoveredNodeId || edge.target === hoveredNodeId) {
        edgeIdSet.add(edge.id);
        nodeIds.add(edge.source);
        nodeIds.add(edge.target);
      }
    }
    return { nodeIds, edgeIds: edgeIdSet };
  }, [hoveredNodeId, isFocusMode, focusView, graph.edges]);

  const displayNodes = useMemo(() => {
    const base = isFocusMode ? (focusView?.nodes || []) : nodes;
    if (!hoverSets) {
      return base;
    }
    return base.map(n => ({
      ...n,
      data: { ...n.data, dimmed: !hoverSets.nodeIds.has(n.id) },
    }));
  }, [isFocusMode, focusView, nodes, hoverSets]);

  const displayEdges = useMemo(() => {
    const base = isFocusMode ? (focusView?.edges || []) : graph.edges;
    return base.map(edge => {
      const highlighted = hoverSets ? hoverSets.edgeIds.has(edge.id) : false;
      const defaultOpacity = isFocusMode ? FOCUS_EDGE_OPACITY_DEFAULT : OVERVIEW_EDGE_OPACITY_DEFAULT;
      const fadedOpacity = isFocusMode ? FOCUS_EDGE_OPACITY_FADED : OVERVIEW_EDGE_OPACITY_FADED;
      const opacity = hoverSets ? (highlighted ? EDGE_OPACITY_HIGHLIGHT : fadedOpacity) : defaultOpacity;
      // 聚焦模式标签常显；全图模式默认隐藏标签，悬停命中才显示，避免默认满屏文字
      const labelOpacity = isFocusMode ? 1 : (highlighted ? 1 : 0);
      return {
        ...edge,
        style: { ...edge.style, opacity, strokeWidth: highlighted ? 2.5 : 1.5 },
        zIndex: highlighted ? 1 : 0,
        labelStyle: { opacity: labelOpacity, fill: 'var(--vscode-foreground)', fontSize: 10 },
        labelBgStyle: { opacity: labelOpacity * 0.9 },
      };
    });
  }, [isFocusMode, focusView, graph.edges, hoverSets]);

  const searchResults = useMemo(() => {
    const q = searchQuery.trim().toLowerCase();
    if (!q) {
      return [];
    }
    return graph.seeds
      .filter(s => s.data.kind === 'view')
      .filter(s => s.data.name.toLowerCase().includes(q) || s.data.fileLabel.toLowerCase().includes(q))
      .slice(0, 30);
  }, [searchQuery, graph.seeds]);

  const selectSearchResult = useCallback((id: string) => {
    setFocusPath([id]);
    setSearchQuery('');
    setSearchOpen(false);
  }, []);

  const onSearchKeyDown = useCallback((e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Escape') {
      setSearchQuery('');
      setSearchOpen(false);
      (e.target as HTMLInputElement).blur();
    } else if (e.key === 'Enter' && searchResults.length > 0) {
      selectSearchResult(searchResults[0].id);
    }
  }, [searchResults, selectSearchResult]);

  if (!visible) {
    return null;
  }

  return (
    <div className="vrm-overlay" onClick={onClose}>
      <div
        className={`vrm-dialog${isInteracting ? ' vrm-dialog-interacting' : ''}`}
        style={{ left: dialogRect.x, top: dialogRect.y, width: dialogRect.width, height: dialogRect.height }}
        onClick={e => e.stopPropagation()}
      >
        <div className="vrm-header" onPointerDown={handleHeaderPointerDown}>
          <div className="vrm-title">
            <span className="vrm-icon">🔗</span>
            {t('View Navigation Relations')}
          </div>
          <div className="vrm-search">
            <Search size={13} className="vrm-search-icon" />
            <input
              type="text"
              className="vrm-search-input"
              placeholder={t('Search views by name or file')}
              aria-label={t('Search views by name or file')}
              value={searchQuery}
              onChange={e => { setSearchQuery(e.target.value); setSearchOpen(true); }}
              onFocus={() => setSearchOpen(true)}
              onBlur={() => setSearchOpen(false)}
              onKeyDown={onSearchKeyDown}
            />
            {searchOpen && searchQuery.trim() && (
              <div className="vrm-search-results" onMouseDown={e => e.preventDefault()}>
                {searchResults.length === 0 ? (
                  <div className="vrm-search-empty">{t('No matching views')}</div>
                ) : (
                  searchResults.map(r => (
                    <div
                      key={r.id}
                      className="vrm-search-result"
                      onClick={() => selectSearchResult(r.id)}
                    >
                      <span className="vrm-search-result-name">{r.data.name}</span>
                      <span className="vrm-search-result-file">{r.data.fileLabel}</span>
                    </div>
                  ))
                )}
              </div>
            )}
          </div>
          <div className="vrm-toolbar">
            <button className="vrm-close" onClick={onClose} title={t('Close')}><X size={18} /></button>
          </div>
        </div>

        {navLayoutSaveError !== null && (
          <div className="vrm-layout-save-warning" role="alert">
            <span>
              {t('Failed to save navigation layout')}
              {navLayoutSaveError ? `: ${navLayoutSaveError}` : ''}
            </span>
            <button
              className="vrm-layout-save-warning-dismiss"
              onClick={clearNavLayoutSaveError}
              title={t('Dismiss')}
              aria-label={t('Dismiss')}
            >
              <X size={12} />
            </button>
          </div>
        )}

        <div className="vrm-canvas">
          {isFocusMode && (
            <div className="vrm-focus-bar">
              <button className="vrm-focus-back" onClick={backToOverview}>
                {`← ${t('Back to full graph')}`}
              </button>
              <div className="vrm-breadcrumb">
                {focusPath.map((id, i) => {
                  const name = seedById.get(id)?.data.name || id;
                  const isLast = i === focusPath.length - 1;
                  return (
                    <span key={id} className="vrm-breadcrumb-segment">
                      {i > 0 && <span className="vrm-breadcrumb-sep">›</span>}
                      {isLast ? (
                        <span className="vrm-breadcrumb-current">{name}</span>
                      ) : (
                        <button className="vrm-breadcrumb-link" onClick={() => jumpToBreadcrumb(i)}>{name}</button>
                      )}
                    </span>
                  );
                })}
              </div>
            </div>
          )}
          {graph.viewCount === 0 ? (
            <div className="vrm-empty">
              <div className="vrm-empty-icon">📭</div>
              <div>{t('No views')}</div>
            </div>
          ) : (
            <ReactFlow<ViewFlowNode, ViewFlowEdge>
              className="vrm-flow"
              nodes={displayNodes}
              edges={displayEdges}
              nodeTypes={nodeTypes}
              onNodesChange={onNodesChange}
              onNodeClick={onNodeClick}
              onNodeDragStop={onNodeDragStop}
              onNodeMouseEnter={onNodeMouseEnter}
              onNodeMouseLeave={onNodeMouseLeave}
              onInit={onInit}
              fitView
              fitViewOptions={{ padding: 0.15 }}
              minZoom={0.05}
              maxZoom={2.5}
              nodesDraggable={!isFocusMode}
              nodesConnectable={false}
              edgesReconnectable={false}
              deleteKeyCode={null}
              ariaLabelConfig={{
                'controls.zoomIn.ariaLabel': t('Zoom In'),
                'controls.zoomOut.ariaLabel': t('Zoom Out'),
                'controls.fitView.ariaLabel': t('Fit to window'),
                'controls.interactive.ariaLabel': t('Toggle interactivity'),
              }}
            >
              <Background variant={BackgroundVariant.Dots} gap={24} size={1.5} />
              <MiniMap pannable zoomable nodeColor={minimapNodeColor} />
              <Controls />
            </ReactFlow>
          )}
        </div>

        <div className="vrm-footer">
          <div className="vrm-legend">
            <span className="vrm-legend-item"><span className="vrm-dot vrm-dot-current" />{t('Current file')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-valid" />{t('Valid connection')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-invalid" />{t('Invalid connection')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-ambiguous" />{t('Ambiguous connection')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-timer" />{t('Timer connection')}</span>
          </div>
          <div className="vrm-stats">
            {t('Views')} {graph.viewCount} · {t('Connections')} {graph.edgeCount}
          </div>
        </div>

        <div
          className="vrm-resize-handle"
          onPointerDown={handleResizePointerDown}
          title={t('Drag to resize')}
          aria-label={t('Drag to resize')}
        />
      </div>
    </div>
  );
};
