import React, { useMemo, useRef, useState, useEffect, useCallback } from 'react';
import { X } from 'lucide-react';
import {
  ReactFlow,
  MiniMap,
  Controls,
  Background,
  BackgroundVariant,
  MarkerType,
  Position,
  Handle,
  applyNodeChanges,
  type Node,
  type Edge,
  type NodeChange,
  type NodeProps,
  type ReactFlowInstance,
} from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { useDesignerStore } from '../store';
import { t } from '../i18n';
import type { ViewInfo } from '../types';
import './ViewRelationModal.css';

interface ViewRelationModalProps {
  visible: boolean;
  onClose: () => void;
}

// 配色统一走主题变量（局部变量在 ViewRelationModal.css 的 .vrm-overlay 上定义，
// 由 --vscode-charts-* 派生并带回退链；禁止硬编码颜色）
const COLOR_VALID = 'var(--vrm-color-valid)';
const COLOR_INVALID = 'var(--vrm-color-invalid)';
const COLOR_AMBIGUOUS = 'var(--vrm-color-ambiguous)';
const COLOR_CURRENT = 'var(--vscode-focusBorder)';
const COLOR_NODE_DEFAULT = 'var(--vscode-editorWidget-border, var(--vscode-panel-border))';

// ---------------- 节点数据模型 ----------------

type ViewNodeKind = 'view' | 'missing' | 'ambiguous';

interface ViewNodeData extends Record<string, unknown> {
  name: string;
  fileLabel: string;      // 文件相对路径（T2 fileRelative；旧数据回退 basename）
  isCurrentFile: boolean;
  kind: ViewNodeKind;     // view=真实屏；missing=无效目标占位；ambiguous=歧义目标占位
  invalidOut: number;     // 出边中无效目标条数
  ambiguousOut: number;   // 出边中歧义目标条数
  autoId: boolean;        // id 为解析器自动生成（建议补显式 id）
}

type ViewFlowNode = Node<ViewNodeData, 'viewCard'>;

// ---------------- 工具函数 ----------------

/** 路径规范化比较（统一正斜杠 + 忽略大小写，Windows 盘符/分隔符差异不敏感） */
const normalizePath = (p: string): string => p.replace(/\\/g, '/').toLowerCase();

/** 节点 id：viewKey 复合键（relPath#viewId）；旧数据回退 file#id */
const nodeIdOf = (view: ViewInfo): string => view.viewKey || `${view.file}#${view.id}`;

/** 解析器确定性 fallback id 形如 `${basename}_hg_view_auto_N` / `hg_view_auto_N` */
const isAutoGeneratedId = (id: string): boolean => /(^|_)hg_view_auto_\d+$/.test(id);

/** 事件类型 → 本地化标签（复用 event.* i18n key，缺失回退原始值） */
const eventLabel = (type: string): string => {
  const key = `event.${type}`;
  const label = t(key as Parameters<typeof t>[0]);
  return label === key ? type : label;
};

// ---------------- 自定义节点：屏卡片 ----------------

const ViewCardNode: React.FC<NodeProps<ViewFlowNode>> = ({ data }) => {
  const classes = ['vrm-node', `vrm-node-${data.kind}`];
  if (data.isCurrentFile) {
    classes.push('vrm-node-current');
  }
  const hasBadges = data.invalidOut > 0 || data.ambiguousOut > 0 || data.autoId;
  return (
    <div className={classes.join(' ')}>
      <Handle type="target" position={Position.Left} className="vrm-handle" isConnectable={false} />
      <div className="vrm-node-name" title={data.name}>
        {data.isCurrentFile && <span className="vrm-node-star">★</span>}
        <span className="vrm-node-name-text">{data.name}</span>
      </div>
      <div className="vrm-node-file" title={data.fileLabel}>
        {data.kind === 'view'
          ? data.fileLabel
          : data.kind === 'missing'
            ? t('Target not found')
            : t('Ambiguous target')}
      </div>
      {hasBadges && (
        <div className="vrm-node-badges">
          {data.invalidOut > 0 && (
            <span className="vrm-badge vrm-badge-invalid" title={t('Has invalid jump target')}>
              ⚠ {data.invalidOut}
            </span>
          )}
          {data.ambiguousOut > 0 && (
            <span className="vrm-badge vrm-badge-ambiguous" title={t('Has ambiguous jump target')}>
              ⚠ {data.ambiguousOut}
            </span>
          )}
          {data.autoId && (
            <span className="vrm-badge vrm-badge-autoid" title={t('View has no id, consider adding one')}>
              id?
            </span>
          )}
        </div>
      )}
      <Handle type="source" position={Position.Right} className="vrm-handle" isConnectable={false} />
    </div>
  );
};

const nodeTypes = { viewCard: ViewCardNode };

// ---------------- 图构建 ----------------

interface GraphSeed {
  id: string;
  data: ViewNodeData;
}

interface GraphModel {
  seeds: GraphSeed[]; // 已按种子布局顺序排序（当前文件优先 → 相对路径 → 名称；占位节点殿后）
  edges: Edge[];
  viewCount: number;
  edgeCount: number;
}

const buildGraph = (allViews: ViewInfo[] | undefined, currentFilePath: string | undefined): GraphModel => {
  const views = allViews || [];
  const cur = currentFilePath ? normalizePath(currentFilePath) : '';

  const isCurrentFile = (v: ViewInfo): boolean => {
    if (!cur) {
      return false;
    }
    if (v.filePath) {
      return normalizePath(v.filePath) === cur;
    }
    // 旧数据无绝对路径：回退 basename 比较
    const base = (cur.split('/').pop() || '').replace(/\.hml$/, '');
    return base !== '' && base === v.file.toLowerCase();
  };

  const fileLabelOf = (v: ViewInfo): string => v.fileRelative || v.file;

  // 种子布局排序：当前文件优先 → 相对路径 → 名称
  const ordered = [...views].sort((a, b) => {
    const aCur = isCurrentFile(a);
    const bCur = isCurrentFile(b);
    if (aCur !== bCur) {
      return aCur ? -1 : 1;
    }
    const fileCmp = fileLabelOf(a).localeCompare(fileLabelOf(b));
    if (fileCmp !== 0) {
      return fileCmp;
    }
    return a.name.localeCompare(b.name);
  });

  const edges: Edge[] = [];
  const edgeIds = new Set<string>();
  // 占位节点：无效 / 歧义目标（保证每条 T2 边都可见）
  const synthetic = new Map<string, GraphSeed>();
  const invalidOutBy = new Map<string, number>();
  const ambiguousOutBy = new Map<string, number>();
  const seenNodeIds = new Set<string>();
  const seeds: GraphSeed[] = [];

  for (const view of ordered) {
    const id = nodeIdOf(view);
    if (seenNodeIds.has(id)) {
      continue; // 防御：复合键理论上唯一
    }
    seenNodeIds.add(id);
    seeds.push({
      id,
      data: {
        name: view.name,
        fileLabel: fileLabelOf(view),
        isCurrentFile: isCurrentFile(view),
        kind: 'view',
        invalidOut: 0,
        ambiguousOut: 0,
        autoId: isAutoGeneratedId(view.id),
      },
    });
  }

  for (const view of ordered) {
    const sourceId = nodeIdOf(view);
    (view.edges || []).forEach((e, ei) => {
      if (!e.target) {
        return;
      }
      const isTimer = e.sourceIsTimer === true || (e.eventType || e.event) === 'timer';
      const invalid = e.isValid === false;
      const ambiguous = e.targetAmbiguous === true;

      let targetNodeId: string;
      if (invalid) {
        targetNodeId = `missing:${e.target}`;
        invalidOutBy.set(sourceId, (invalidOutBy.get(sourceId) || 0) + 1);
      } else if (ambiguous || !e.targetViewKey) {
        // 歧义（或旧数据未解析出目标复合键）→ 歧义占位节点
        targetNodeId = `ambiguous:${e.target}`;
        ambiguousOutBy.set(sourceId, (ambiguousOutBy.get(sourceId) || 0) + 1);
      } else {
        targetNodeId = e.targetViewKey;
      }

      if (targetNodeId.startsWith('missing:') || targetNodeId.startsWith('ambiguous:')) {
        if (!synthetic.has(targetNodeId)) {
          synthetic.set(targetNodeId, {
            id: targetNodeId,
            data: {
              name: e.target,
              fileLabel: '',
              isCurrentFile: false,
              kind: targetNodeId.startsWith('missing:') ? 'missing' : 'ambiguous',
              invalidOut: 0,
              ambiguousOut: 0,
              autoId: false,
            },
          });
        }
      }

      // 边标签：触发控件 · 手势（定时器边标注"定时器触发"）
      const controlPart = e.sourceIsView
        ? t('Screen')
        : (e.sourceControlName || e.sourceControlId || '');
      const triggerPart = isTimer ? t('Timer trigger') : eventLabel(e.eventType || e.event);
      const label = controlPart ? `${controlPart} · ${triggerPart}` : triggerPart;

      const color = invalid ? COLOR_INVALID : ambiguous ? COLOR_AMBIGUOUS : COLOR_VALID;
      let edgeId = e.edgeId || `${sourceId}->${e.target}@${ei}`;
      if (edgeIds.has(edgeId)) {
        edgeId = `${edgeId}@${ei}`;
      }
      edgeIds.add(edgeId);

      const classNames = ['vrm-edge'];
      if (invalid) {
        classNames.push('vrm-edge-invalid');
      } else if (ambiguous) {
        classNames.push('vrm-edge-ambiguous');
      }
      if (isTimer) {
        classNames.push('vrm-edge-timer');
      }

      edges.push({
        id: edgeId,
        source: sourceId,
        target: targetNodeId,
        label,
        className: classNames.join(' '),
        style: {
          stroke: color,
          strokeWidth: 1.5,
          ...(isTimer ? { strokeDasharray: '6 4' } : {}),
        },
        markerEnd: { type: MarkerType.ArrowClosed, color, width: 16, height: 16 },
      });
    });
  }

  // 回填出边告警计数
  for (const seed of seeds) {
    seed.data.invalidOut = invalidOutBy.get(seed.id) || 0;
    seed.data.ambiguousOut = ambiguousOutBy.get(seed.id) || 0;
  }

  // 占位节点殿后，按名称排序
  const syntheticSeeds = [...synthetic.values()].sort((a, b) => a.data.name.localeCompare(b.data.name));

  return {
    seeds: [...seeds, ...syntheticSeeds],
    edges,
    viewCount: views.length,
    edgeCount: edges.length,
  };
};

// 种子网格布局：≈√(1.6n) 列的紧凑网格（同文件 view 因排序相邻聚拢）
const GRID_CELL_W = 260;
const GRID_CELL_H = 130;

const seedNodes = (
  seeds: GraphSeed[],
  savedPositions: Map<string, { x: number; y: number }>
): ViewFlowNode[] => {
  const cols = Math.max(1, Math.round(Math.sqrt(seeds.length * 1.6)));
  return seeds.map((seed, i) => ({
    id: seed.id,
    type: 'viewCard' as const,
    position: savedPositions.get(seed.id) || {
      x: (i % cols) * GRID_CELL_W,
      y: Math.floor(i / cols) * GRID_CELL_H,
    },
    data: seed.data,
  }));
};

const minimapNodeColor = (node: Node): string => {
  const data = node.data as ViewNodeData | undefined;
  if (data?.kind === 'missing') {
    return COLOR_INVALID;
  }
  if (data?.kind === 'ambiguous') {
    return COLOR_AMBIGUOUS;
  }
  if (data?.isCurrentFile) {
    return COLOR_CURRENT;
  }
  return COLOR_NODE_DEFAULT;
};

// ---------------- 弹窗组件 ----------------

export const ViewRelationModal: React.FC<ViewRelationModalProps> = ({ visible, onClose }) => {
  const allViews = useDesignerStore(s => s.allViews);
  const currentFilePath = useDesignerStore(s => s.currentFilePath);
  const refreshNavGraph = useDesignerStore(s => s.refreshNavGraph);

  const [nodes, setNodes] = useState<ViewFlowNode[]>([]);
  // 拖动位置暂存（组件内存态；持久化到 .honeygui/nav-layout.json 是 T7）
  const positionsRef = useRef(new Map<string, { x: number; y: number }>());
  const rfInstanceRef = useRef<ReactFlowInstance<ViewFlowNode, Edge> | null>(null);
  const lastSigRef = useRef('');

  // 打开弹窗即请求宿主重扫导航图（allViews 常驻 store，多面板同开时会陈旧）
  useEffect(() => {
    if (visible) {
      refreshNavGraph();
    }
  }, [visible, refreshNavGraph]);

  const graph = useMemo(() => buildGraph(allViews, currentFilePath), [allViews, currentFilePath]);

  // 打开期间重扫结果到达 → 重建节点（保留用户已拖动的位置）；
  // 节点集合变化时重新 fitView
  useEffect(() => {
    if (!visible) {
      return;
    }
    setNodes(seedNodes(graph.seeds, positionsRef.current));
    const sig = graph.seeds.map(s => s.id).join('|');
    if (sig !== lastSigRef.current) {
      lastSigRef.current = sig;
      window.requestAnimationFrame(() => {
        rfInstanceRef.current?.fitView({ padding: 0.15 });
      });
    }
  }, [visible, graph]);

  const onNodesChange = useCallback((changes: NodeChange<ViewFlowNode>[]) => {
    setNodes(nds => applyNodeChanges(changes, nds));
    for (const change of changes) {
      if (change.type === 'position' && change.position) {
        positionsRef.current.set(change.id, change.position);
      }
    }
  }, []);

  const onInit = useCallback((instance: ReactFlowInstance<ViewFlowNode, Edge>) => {
    rfInstanceRef.current = instance;
  }, []);

  if (!visible) {
    return null;
  }

  return (
    <div className="vrm-overlay" onClick={onClose}>
      <div className="vrm-dialog" onClick={e => e.stopPropagation()}>
        <div className="vrm-header">
          <div className="vrm-title">
            <span className="vrm-icon">🔗</span>
            {t('View Navigation Relations')}
          </div>
          <div className="vrm-toolbar">
            <button className="vrm-close" onClick={onClose} title={t('Close')}><X size={18} /></button>
          </div>
        </div>

        <div className="vrm-canvas">
          {graph.viewCount === 0 ? (
            <div className="vrm-empty">
              <div className="vrm-empty-icon">📭</div>
              <div>{t('No views')}</div>
            </div>
          ) : (
            <ReactFlow<ViewFlowNode, Edge>
              className="vrm-flow"
              nodes={nodes}
              edges={graph.edges}
              nodeTypes={nodeTypes}
              onNodesChange={onNodesChange}
              onInit={onInit}
              fitView
              fitViewOptions={{ padding: 0.15 }}
              minZoom={0.05}
              maxZoom={2.5}
              nodesConnectable={false}
              edgesReconnectable={false}
              deleteKeyCode={null}
              ariaLabelConfig={{
                'controls.zoomIn.ariaLabel': t('Zoom In'),
                'controls.zoomOut.ariaLabel': t('Zoom Out'),
                'controls.fitView.ariaLabel': t('Fit to window'),
                'controls.interactive.ariaLabel': t('Toggle interactivity'),
              }}
            >
              <Background variant={BackgroundVariant.Dots} gap={24} size={1.5} />
              <MiniMap pannable zoomable nodeColor={minimapNodeColor} />
              <Controls />
            </ReactFlow>
          )}
        </div>

        <div className="vrm-footer">
          <div className="vrm-legend">
            <span className="vrm-legend-item"><span className="vrm-dot vrm-dot-current" />{t('Current file')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-valid" />{t('Valid connection')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-invalid" />{t('Invalid connection')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-ambiguous" />{t('Ambiguous connection')}</span>
            <span className="vrm-legend-item"><span className="vrm-line vrm-line-timer" />{t('Timer connection')}</span>
          </div>
          <div className="vrm-stats">
            {t('Views')} {graph.viewCount} · {t('Connections')} {graph.edgeCount}
          </div>
        </div>
      </div>
    </div>
  );
};
